/** This file is generated automatically. Do not modify it.
 */
#include <ofsys.h>




/* G */
const char *
translate_OFERROR_desc( ofuint32 enumValue )
{
    struct NAMEPAIR { ofint32 index; char *name; };
    NAMEPAIR names[] = {
        { ERR_SUCCESS, (char*)"Success." },
        { ERR_INVAL_PROTMETH, (char*)"Invalid protocol/method." },
        { ERR_COMPILE_ERROR, (char*)"Compilation error(s)." },
        { ERR_INVAL_CLASS, (char*)"Unknown class." },
        { ERR_INVAL_OBJECT, (char*)"Unknown object." },
        { ERR_PROXY_CONNECT, (char*)"Error connecting to the server." },
        { ERR_INT_EXEC_FAIL, (char*)"Internal execution failure." },
        { ERR_ACCDEN, (char*)"Access denied." },
        { ERR_ENTITY_EXIST, (char*)"Entity (class or object) already exists." },
        { ERR_ENTITY_NOTFOUND, (char*)"Entity (class or object) not found." },
        { ERR_OBJSTORE_BUSY, (char*)"Object storage is busy." },
        { ERR_NOTIMPL, (char*)"Function not implemented." },
        { ERR_INT_DBMS, (char*)"Internal DBMS error." },
        { ERR_AOM_INT, (char*)"Internal active object map error." },
        { ERR_SUCCESS_WITH_INFO, (char*)"Flagged success." },
        { ERR_INT_EXEC_ASSERT, (char*)"Internal execution assert." },
        { ERR_DIVIDE_BY_ZERO, (char*)"Division by zero." },
        { ERR_EXEC_STACK_UNDER, (char*)"Execution stack underflow." },
        { ERR_AOM_OBJECT_INT, (char*)"Internal active object error." },
        { ERR_EXEC_UNDEF_VAR, (char*)"Undefined variable in execution." },
        { ERR_FILE_OPEN_ERR, (char*)"Error opening file." },
        { ERR_LIB_NOSYM, (char*)"A required symbol was not found in the library." },
        { ERR_CLM_ERROR, (char*)"An error occured communicating with a CLM." },
        { ERR_METH_PARAM_COUNT, (char*)"Method parameter count mismatch." },
        { ERR_INVAL_METHOD, (char*)"Method invalid within class." },
        { ERR_INVAL_PROPERTY, (char*)"Property not found." },
        { ERR_FIELD_NOTEXIST, (char*)"A required header field was not found." },
        { ERR_INST_NOTEXIST, (char*)"The named instance does not exist." },
        { ERR_INST_ALREADY_RUN, (char*)"The named instance is already running." },
        { ERR_INST_NOT_RUN, (char*)"The named instance is not running." },
        { ERR_SYSTEM_INSTANCE, (char*)"The named instance is a system instance." },
        { ERR_LIB_NOCLASSLIST, (char*)"The class list could not be retrieved from a library." },
        { ERR_LIB_ERROR, (char*)"A general error occured while dealing with a server library." },
        { ERR_LIB_NOT_CREATE_CLASS, (char*)"The library did not create the requested class." },
        { ERR_OBJECT_HAS_CHILDREN, (char*)"The current operation cannot be performed on object's that have children." },
        { ERR_CLASS_HAS_CHILDREN, (char*)"The current operation cannot be performed on class' that have children." },
        { ERR_CANT_DESTROY_ROOT, (char*)"You cannot destroy the root class or object." },
        { ERR_CANT_DESTROY_SYSTEM_OBJECT, (char*)"You cannot destroy a system object." },
        { ERR_CANT_DESTROY_SYSTEM_CLASS, (char*)"You cannot destroy a system class." },
        { ERR_INVAL_LIB_ALIAS, (char*)"The supplied library alias is invalid." },
        { ERR_INVAL_SUB_FUNCTION, (char*)"The sub-function was not recognized." },
        { ERR_INVAL_COLONEL_FUNCTION, (char*)"The specified function id was invalid." },
        { ERR_INVAL_DATA_ID, (char*)"The data identity specified does not exist." },
        { ERR_ELVIS_ERROR, (char*)"An error occurred within Elvis." },
        { ERR_INVAL_USERPASS, (char*)"Invalid username or password." },
        { ERR_SESSION_INVALID, (char*)"The specified session is invalid." },
        { ERR_NETWORK_FAILED, (char*)"The network has failed in transaction." },
        { ERR_DEADLOCK_ABORT, (char*)"The transaction has been aborted due to deadlock." },
        { ERR_INVAL_PARENT, (char*)"The parent given is not a valid object." },
        { ERR_INVAL_NAME, (char*)"The name given is already in use." },
        { ERR_INVAL_FILE_HANDLE, (char*)"The handle supplied is invalid." },
        { ERR_OFSOCKET_ERROR, (char*)"The server has encountered a socket error." },
        { ERR_INT_OFOR, (char*)"Internal OpenFabric Object Repository error." },
        { ERR_CLM_NO_OFAP_MSG, (char*)"The CLM could not retrieve the OFAP message." },
        { ERR_CLM_XSL_TRANSFORM_FAILED, (char*)"The CLM could not perform the XSL transformation." },
        { ERR_SOCKET_TIMEOUT, (char*)"The socket timed out while sending or receiving." },
        { ERR_UNLOCATABLE, (char*)"The server could not be located." },
        { ERR_LDAP_CONNECTION, (char*)"Could not connect or disconnect from LDAP server." },
        { ERR_LDAP_ENTRY, (char*)"LDAP entry not found." },
        { ERR_LDAP_ATTRIBUTE, (char*)"LDAP attribute not found." },
        { ERR_LDAP_ADD, (char*)"Could not add entry to LDAP server." },
        { ERR_LDAP_DELETE, (char*)"Could not delete entry from LDAP server." },
        { ERR_LDAP_MODIFY, (char*)"Could not modify LDAP entry." },
        { ERR_NEW_ID, (char*)"Could not create new id." },
        { ERR_AUTHENTICATION_FAILURE, (char*)"Entity could not be authenticated." },
        { ERR_SERIAL_FILE, (char*)"Could not load certificate serial number or rename file." },
        { ERR_MEMORY_ALLOCATION, (char*)"Memory allocation failure." },
        { ERR_CERT_REQUEST, (char*)"Could not read certificate request." },
        { ERR_CERT_REQUEST_FORMAT, (char*)"Certificate request has wrong format or signature." },
        { ERR_EMAIL_FORMAT, (char*)"Email address in certificate request has wrong format." },
        { ERR_ILLEGAL_CHARACTERS, (char*)"The certificate request contains characters that are illegal for the ASN.1 type." },
        { ERR_REQUIRED_FIELD_MISSING, (char*)"A required field in certificate request is missing." },
        { ERR_MATCHING_FIELD_MISSING, (char*)"A matching field in certificate request is missing." },
        { ERR_CA_FIELD_MISSING, (char*)"Missing field in CA certificate." },
        { ERR_MATCHING_FIELD, (char*)"Required field in certificate request does not match CA certificate." },
        { ERR_INVALID_TYPE_IN_POLICY, (char*)"An invalid type exists in the CA policy." },
        { ERR_USER_NAME_EXISTS, (char*)"The user name already exists." },
        { ERR_USER_NAME_DOES_NOT_EXIST, (char*)"The user name does not exist." },
        { ERR_USER_NAME_REQUIRED, (char*)"A user name is required for this user." },
        { ERR_ID_EXISTS, (char*)"The server already exists." },
        { ERR_ID_DOES_NOT_EXIST, (char*)"The server does not exist." },
        { ERR_INVALID_CERT, (char*)"Certificate has wrong format." },
        { ERR_SIGNING_FAILED, (char*)"Could not sign data." },
        { ERR_CERT_EXPIRED, (char*)"The certificate has expired." },
        { ERR_CERT_REVOKED, (char*)"The certificate has been revoked." },
        { ERR_CERT_REQUIRED, (char*)"A certificate is required for this user." },
        { ERR_INVALID_SIGNATURE, (char*)"The signature supplied with this user token is invalid." },
        { ERR_REF_COUNT_CHANGE, (char*)"The reference count could not be updated." },
        { ERR_CONNECTION_ERROR, (char*)"Could not connect to server." },
        { ERR_NOT_AUTHENTICATED, (char*)"The user or server has not been authenticated yet." },
        { ERR_REGISTRY_INFO, (char*)"The address or port numbers for the registry could not be found." },
        { ERR_NO_CONTACT_REGISTRY, (char*)"Could not contact the registry." },
        { ERR_NO_CONTACT_SENTINEL, (char*)"Could not contact the sentinel server." },
        { ERR_NO_CONTACT_ACCESS, (char*)"Could not contact the access manager." },
        { ERR_NO_CONTACT_COMPONENT, (char*)"Could not contact the required component." },
        { ERR_REGISTRY_INVAL_SERVER, (char*)"Invalid server (from registry)" },
        { ERR_REGISTRY_INVAL_USER, (char*)"Invalid user (from registry)" },
        { ERR_NAME_NOT_SET, (char*)"The server name to connect to has not been specified." },
        { ERR_INVALID_TOKEN, (char*)"The authentication token is invalid." },
        { ERR_ILLEGAL_ACTION, (char*)"The action is not a legal operation for the registry or authentication server." },
        { ERR_ILLEGAL_FIELD, (char*)"A field in the message is illegal." },
        { ERR_PRIVATE_KEY, (char*)"Could not create private key." },
        { ERR_WRITE_PRIVATE_KEY, (char*)"Could not write private key." },
        { ERR_SIGN_REQ, (char*)"Could not sign certificate request." },
        { ERR_WRITE_REQ, (char*)"Could not write certificate request." },
        { ERR_REQ_VERSION, (char*)"Could not set certificate request version." },
        { ERR_ADD_SUBJECT_FIELD, (char*)"Could not add subject field to certificate request." },
        { ERR_WRITE_CERT, (char*)"Could not write certificate." },
        { ERR_CERT_OR_PRIV_KEY, (char*)"Could not set certificate or private key for socket." },
        { ERR_REPLACE_NAME, (char*)"Could not replace the common name in certificate." },
        { ERR_ADDRESS, (char*)"The address or port numbers for the server are invalid." },
        { ERR_IP_ADDRESS, (char*)"The message IP address does not match the IP address for this session." },
        { ERR_CANNOT_ADD_EXTENSION, (char*)"Certificate extension cannot be added." },
        { ERR_AUTHENTICATION_REQUIRED, (char*)"User must be authenticated." },
        { ERR_VERIFY_FAILED, (char*)"Could not verify authentication token signature." },
        { ERR_RESPONDER_NOT_EXISTS, (char*)"Could not find responder." },
        { ERR_INVALID_RESP_METHOD, (char*)"The responder could not handle the method." },
        { ERR_CONFIG_FILE, (char*)"Could not access config file." },
        { ERR_SSL_CONNECT, (char*)"Could not establish SSL connection with server." },
        { ERR_SSL_CERT, (char*)"Server certificate is invalid or has wrong server id." },
        { ERR_SSL_PRIVKEY, (char*)"Server private key is invalid or could not be loaded." },
        { ERR_SSL_CERTKEY_MISMATCH, (char*)"Server certificate and key do not match." },
        { ERR_SSL_SERIALFILE_ERROR, (char*)"An error occured accessing the serial number file." },
        { ERR_SCHEDULER_INVAL_TASK, (char*)"Invalid task index." },
        { ERR_SSL_CONNECTION_REQUIRED, (char*)"SSL Connection required for specified operation." },
        { ERR_REG_NO_ID_LEFT, (char*)"No identities available for requested pool." },
        { ERR_INVAL_LIC_FORMAT, (char*)"Invalid licence file format." },
        { ERR_COMMIT_INCOMPLETE, (char*)"Distributed transaction not commited on all machines/" },
        { ERR_WAIT_FOR, (char*)"Internal use only - transaction must wait for another." },
        { ERR_NOT_LOCAL, (char*)"Internal use only - remote field not on remote machine." },
        { ERR_SICK, (char*)"Internal use only - server has reached unreachable code." },
        { ERR_INVAL_REQUEST, (char*)"Invalid network request received by repository." },
        { ERR_BAD_LINK, (char*)"Bad link object." },
        { ERR_INVAL_TRANSACTION, (char*)"Transaction not a valid one." },
        { ERR_LOCAL_LINK, (char*)"Link is to a local object." },
        { ERR_PROXY_INTERNAL, (char*)"Proxy internal error." },
        { ERR_EMPTY_ACL, (char*)"The entity does not contain the requested ACL." },
        { ERR_INVAL_EXEC_CONTEXT, (char*)"Invalid execution context." },
        { ERR_TRANSACTION_DEAD, (char*)"Transaction being used is no longer running." },
        { ERR_UNKNOWN_ACLMAN_FUNC, (char*)"Unknown acl management function." },
        { ERR_XML_ERROR_PARSING_INPUT_FILE, (char*)"Error parsing input xml file." },
        { ERR_XML_ERROR_PARSING_WSDL_FILE, (char*)"Error parsing WSDL file." },
        { ERR_XML_ERROR_PARSING_WSDL_IMPORT_FILE, (char*)"Error parsing WSDL IMPORT file." },
        { ERR_XML_ERROR_PARSING_XSLT_STYLESHEET, (char*)"Error parsing XSLT stylesheet." },
        { ERR_XML_CANNOT_RETRIEVE_WSDL_FILE, (char*)"Unable to retrieve WSDL file." },
        { ERR_XSLT_TRANSFORM, (char*)"Error perfoming xslt transform." },
        { ERR_XSLT_TRANSFORM_RELATED, (char*)"Error related to perfoming xslt transform." },
        { ERR_SOAP_ERROR_LOADING_OBJECT, (char*)"Unable to retrieve data from object." },
        { ERR_WSDL_ERROR_PARSING_COMPLEX_TYPES, (char*)"Error parsing WSDL complex types." },
        { ERR_WSDL_CXT_COMPILE_FAILED, (char*)"Compile of complex Types failed." },
        { ERR_WSDL_CLASS_COMPILE_FAILED, (char*)"Compile of WSDL Class failed." },
        { ERR_WSDL_CANNOT_CREATE_CLASS, (char*)"Unable to create class from WSDL." },
        { ERR_WSDL_CANNOT_FIND_DEFAULT_NAMESPACE_IN_WSDL_FILE, (char*)"Missing Document or default XML namespace in WSDL document." },
        { ERR_WSDL_CANNOT_FIND_XMLSCHEMA_NAMESPACE_IN_WSDL_FILE, (char*)"Missing default XMLSchema namespace in WSDL document." },
        { ERR_WSDL_CANNOT_FIND_DEFAULT_NAMESPACE_IN_WSDL_IMPORT_FILE, (char*)"Missing default XML namespace in WSDL IMPORT document." },
        { ERR_WSDL_CANNOT_FIND_XMLSCHEMA_NAMESPACE_IN_WSDL_IMPORT_FILE, (char*)"Missing default XMLSchema namespace in WSDL IMPORT document." },
        { ERR_WSDL_CANNOT_FIND_NAMESPACE_IN_WSDL_IMPORT_TAG, (char*)"Missing namespace attribute in WSDL IMPORT tag." },
        { ERR_WSDL_CANNOT_FIND_LOCATION_IN_WSDL_IMPORT_TAG, (char*)"Missing location attribute in WSDL IMPORT tag." },
        { ERR_WSDL_ERROR_ADDING_CHILD_NODE_FROM_WSDL_IMPORT_FILE, (char*)"Error adding child node from WSDL IMPORT document." },
        { ERR_WSDL_NOTHING_TO_IMPORT_FROM_WSDL_IMPORT_FILE, (char*)"Nothing found to import in WSDL IMPORT document." },
        { ERR_WSDL_CANNOT_FIND_SERVICE_NAME, (char*)"Missing Service name in WSDL document." },
        { ERR_WSDL_CANNOT_FIND_ANY_PORTS, (char*)"Missing Ports in WSDL Document." },
        { ERR_WSDL_CANNOT_FIND_BINDING_ATTRIBUTE_FOR_PORT, (char*)"Missing binding attribute for Port in WSDL document." },
        { ERR_WSDL_CANNOT_FIND_LOCATION_FOR_PORT, (char*)"Missing location for Port in WSDL document." },
        { ERR_WSDL_CANNOT_FIND_BINDING_TYPE, (char*)"Missing Binding for Port in WSDL document." },
        { ERR_WSDL_CANNOT_FIND_BINDING_OPERATIONS, (char*)"Missing Binding Operations in WSDL document." },
        { ERR_WSDL_MISSING_SOAP_ACTION, (char*)"Missing soapAction in WSDL Document." },
        { ERR_WSDL_CANNOT_FIND_PORTTYPE_OPERATIONS, (char*)"Missing portType Operations in WSDL document." },
        { ERR_WSDL_MISSING_ATTRIBUTE_FOR_COMPLEX_TYPE, (char*)"Missing name attribute for element or complexType in WSDL document." },
        { ERR_WSDL_ERROR_ADDING_CONTAINER_CLASS, (char*)"Error adding container class." },
        { ERR_WSDL_ERROR_ADDING_BASE_CLASS, (char*)"Error adding base class." },
        { ERR_WSDL_ERROR_ADDING_COMPLEXTYPE_CLASS, (char*)"Error adding complexType class." },
        { ERR_WSDL_ERROR_PARSING_COMPLEXTYPE_NAMES_FILE, (char*)"Cannot parse complex type names file." },
        { ERR_WSDL_ERROR_PARSING_COMPLEXTYPE_SLICER_FILE, (char*)"Cannot parse complex type slicer file." },
        { ERR_WSDL_FAILED_TO_RESOLVE_METHOD_RETURN_COMPLEXTYPE_REFERENCE, (char*)"Failed to resolve method return complexType reference to an openFabric class." },
        { ERR_WSDL_FAILED_TO_RESOLVE_PARAMETER_COMPLEXTYPE_REFERENCE, (char*)"Failed to resolve parameter complexType reference to an openFabric class." },
        { ERR_WSDL_FAILED_TO_RESOLVE_METHOD, (char*)"ailed to resolve method reference." },
        { ERR_WSDL_FAILED_TO_RESOLVE_PROPERTY_COMPLEXTYPE_REFERENCE, (char*)"Failed to resolve property complexType reference to an openFabric class." },
        { ERR_WSDL_XSLT_TRANSFORM_FAILED, (char*)"Failed to complete XSLT transform." },
        { ERR_WSDL_FAILED_TO_DETERMINE_TYPE_OF_WSDL_FILE, (char*)"Failed to recognise type of WSDL file." },
        { ERR_WSDL_FAILED_TO_OBTAIN_CLSGUARD, (char*)"Failed to obtain ActiveClassGuard." },
        { ERR_WSDL_ERROR_PARSING_WSDLCXTPREPROCESS_SLICER_FILE, (char*)"Cannot parse wsdl complexType preprocess stylesheet." },
        { ERR_WSDL_ERROR_PARSING_WSDLPREPROCESS_SLICER_FILE, (char*)"Cannot parse wsdl preprocess stylesheet." },
        { ERR_WSDL_NO_URI, (char*)"Cannot parse A NULL WSDL URI." },
        { ERR_ERROR_APPLYING_WSDL_ANALYSE_STYLESHEET, (char*)"Applying wsdl_analyse stylesheet returns NULL." },
        { ERR_ERROR_APPLYING_WSDL_CXT_ANALYSE_STYLESHEET, (char*)"Applying wsdl_complexType_analyse stylesheet returns NULL." },
        { ERR_ERROR_APPLYING_WSDL_CXT_SLICER_STYLESHEET, (char*)"Applying wsdl_cxt_slicer stylesheet returns NULL." },
        { ERR_ERROR_APPLYING_WSDL_IMPORTS_ANALYSE_STYLESHEET, (char*)"Applying wsdl_imports_analyse stylesheet returns NULL." },
        { ERR_ERROR_APPLYING_WSDL_CXT_NAMES_STYLESHEET, (char*)"Applying wsdl_cxt_names stylesheet returns NULL." },
        { ERR_ERROR_APPLYING_PREPROCESS_STYLESHEET, (char*)"Applying wsdl_preprocess stylesheet returns NULL." },
        { ERR_ERROR_APPLYING_CXT_PREPROCESS_STYLESHEET, (char*)"Applying wsdl_cxt_preprocess stylesheet returns NULL." },
        { ERR_ACCESS_TOKEN_NOT_FOUND, (char*)"The message did not contain a relevant access token." },
        { ERR_WSDL_CANNOT_RE_ADD_CLASS, (char*)"Failed to re-add class to repository after type resolution." },
        { ERR_SOAP_CALL_TO_REMOTE_SERVER_FAILED, (char*)"Call to remote SOAP server failed." },
        { ERR_SOAP_REMOTE_SERVER_RETURNED_INVALID_RESPONSE, (char*)"Remote SOAP server returned invalid response." },
        { ERR_SOAP_FAILED_TO_FIND_OPERATION_NAMESPACE, (char*)"Missing operation namespace." },
        { ERR_SOAP_FAILED_TO_PARSE_RESPONSE, (char*)"Failed to parse SOAP server response." },
        { ERR_SOAP_FAILED_TO_RESOLVE_OPERATION_NAME, (char*)"ailed to resolve operation name returned by SOAP server." },
        { ERR_SOAP_FAILED_TO_FIND_SOAP_ACTION, (char*)"Failed to find SOAP Action." },
        { ERR_SOAP_FAILED_TO_FIND_LOCATION, (char*)"Failed to find location." },
        { ERR_SOAP_FAILED_TO_FIND_NAMESPACE_FOR_OPERATION, (char*)"Failed to find namespace for operation." },
        { ERR_SOAP_FAILED_TO_FIND_RESPONSE_RETURN_VALUE, (char*)"Failed to find return value(s) in SOAP response." },
        { ERR_SOAP_SOAP_FAULT_RETURNED, (char*)"SOAP Fault Code returned." },
        { ERR_TOKEN_EXPIRED, (char*)"The supplied token has expired." },
        { ERR_ADDRESS_INVALID, (char*)"The address supplied (OFProxy/OFSocket) is invalid." },
        { ERR_INVAL_QUEUE, (char*)"The supplied queue is invalid." },
        { ERR_NO_MESSAGES, (char*)"There are no available messages." },
        { ERR_INVAL_LISTENER, (char*)"The supplied listener is invalid." },
        { ERR_ALREADY_REGISTERED, (char*)"The supplied listener is already registered for the supplied subject." },
        { ERR_INVAL_EVENT, (char*)"Invalid or unsupported event." },
        { ERR_OUT_OF_RANGE, (char*)"Supplied value is out of a required range." },
        { ERR_INVAL_FORMAT, (char*)"The current format is invalid for the specified operation." },
        { ERR_OFAP_MSG_MALFORMED, (char*)"The incoming message is malformed." },
        { ERR_INVALID_INDEX, (char*)"The supplied index is invalid." },
        { ERR_EPERM, (char*)"System error - Operation not permitted" },
        { ERR_ENOENT, (char*)"System error - No such file or directory" },
        { ERR_ESRCH, (char*)"System error - No such process" },
        { ERR_EINTR, (char*)"System error - Interrupted system call" },
        { ERR_EIO, (char*)"System error - I/O error" },
        { ERR_ENXIO, (char*)"System error - No such device or address" },
        { ERR_E2BIG, (char*)"System error - Arg list too long" },
        { ERR_ENOEXEC, (char*)"System error - Exec format error" },
        { ERR_EBADF, (char*)"System error - Bad file number" },
        { ERR_ECHILD, (char*)"System error - No child processes" },
        { ERR_EAGAIN, (char*)"System error - Try again" },
        { ERR_ENOMEM, (char*)"System error - Out of memory" },
        { ERR_EACCES, (char*)"System error - Permission denied" },
        { ERR_EFAULT, (char*)"System error - Bad address" },
        { ERR_ENOTBLK, (char*)"System error - Block device required" },
        { ERR_EBUSY, (char*)"System error - Device or resource busy" },
        { ERR_EEXIST, (char*)"System error - File exists" },
        { ERR_EXDEV, (char*)"System error - Cross-device link" },
        { ERR_ENODEV, (char*)"System error - No such device" },
        { ERR_ENOTDIR, (char*)"System error - Not a directory" },
        { ERR_EISDIR, (char*)"System error - Is a directory" },
        { ERR_EINVAL, (char*)"System error - Invalid argument" },
        { ERR_ENFILE, (char*)"System error - File table overflow" },
        { ERR_EMFILE, (char*)"System error - Too many open files" },
        { ERR_ENOTTY, (char*)"System error - Not a typewriter" },
        { ERR_ETXTBSY, (char*)"System error - Text file busy" },
        { ERR_EFBIG, (char*)"System error - File too large" },
        { ERR_ENOSPC, (char*)"System error - No space left on device" },
        { ERR_ESPIPE, (char*)"System error - Illegal seek" },
        { ERR_EROFS, (char*)"System error - Read-only file system" },
        { ERR_EMLINK, (char*)"System error - Too many links" },
        { ERR_EPIPE, (char*)"System error - Broken pipe" },
        { ERR_EDOM, (char*)"System error - Math argument out of domain of func" },
        { ERR_ERANGE, (char*)"System error - Math result not representable" },
        { ERR_EDEADLK, (char*)"System error - Resource deadlock would occur" },
        { ERR_ENAMETOOLONG, (char*)"System error - File name too long" },
        { ERR_ENOLCK, (char*)"System error - No record locks available" },
        { ERR_ENOSYS, (char*)"System error - Function not implemented" },
        { ERR_ENOTEMPTY, (char*)"System error - Directory not empty" },
        { ERR_ELOOP, (char*)"System error - Too many symbolic links encountered" },
        { ERR_EWOULDBLOCK, (char*)"System error - Operation would block" },
        { ERR_ENOMSG, (char*)"System error - No message of desired type" },
        { ERR_EIDRM, (char*)"System error - Identifier removed" },
        { ERR_ECHRNG, (char*)"System error - Channel number out of range" },
        { ERR_EL2NSYNC, (char*)"System error - Level not synchronized" },
        { ERR_EL3HLT, (char*)"System error - Level halted" },
        { ERR_EL3RST, (char*)"System error - Level reset" },
        { ERR_ELNRNG, (char*)"System error - Link number out of range" },
        { ERR_EUNATCH, (char*)"System error - Protocol driver not attached" },
        { ERR_ENOCSI, (char*)"System error - No CSI structure available" },
        { ERR_EL2HLT, (char*)"System error - Level 2 halted" },
        { ERR_EBADE, (char*)"System error - Invalid exchange" },
        { ERR_EBADR, (char*)"System error - Invalid request descriptor" },
        { ERR_EXFULL, (char*)"System error - Exchange full" },
        { ERR_ENOANO, (char*)"System error - No anode" },
        { ERR_EBADRQC, (char*)"System error - Invalid request code" },
        { ERR_EBADSLT, (char*)"System error - Invalid slot" },
        { ERR_EDEADLOCK, (char*)"System error - Dead lock" },
        { ERR_EBFONT, (char*)"System error - Bad font file format" },
        { ERR_ENOSTR, (char*)"System error - Device not a stream" },
        { ERR_ENODATA, (char*)"System error - No data available" },
        { ERR_ETIME, (char*)"System error - Timer expired" },
        { ERR_ENOSR, (char*)"System error - Out of streams resources" },
        { ERR_ENONET, (char*)"System error - Machine is not on the network" },
        { ERR_ENOPKG, (char*)"System error - Package not installed" },
        { ERR_EREMOTE, (char*)"System error - Object is remote" },
        { ERR_ENOLINK, (char*)"System error - Link has been severed" },
        { ERR_EADV, (char*)"System error - Advertise error" },
        { ERR_ESRMNT, (char*)"System error - Srmount error" },
        { ERR_ECOMM, (char*)"System error - Communication error on send" },
        { ERR_EPROTO, (char*)"System error - Protocol error" },
        { ERR_EMULTIHOP, (char*)"System error - Multihop attempted" },
        { ERR_EDOTDOT, (char*)"System error - RFS specific error" },
        { ERR_EBADMSG, (char*)"System error - Not a data message" },
        { ERR_EOVERFLOW, (char*)"System error - Value too large for d data type" },
        { ERR_ENOTUNIQ, (char*)"System error - Name not unique on network" },
        { ERR_EBADFD, (char*)"System error - File descriptor in bad state" },
        { ERR_EREMCHG, (char*)"System error - Remote address changed" },
        { ERR_ELIBACC, (char*)"System error - Can not access a needed shared library" },
        { ERR_ELIBBAD, (char*)"System error - Accessing a corrupted shared library" },
        { ERR_ELIBSCN, (char*)"System error - .lib section in a.out corrupted" },
        { ERR_ELIBMAX, (char*)"System error - Attempting to link in too many shared libraries" },
        { ERR_ELIBEXEC, (char*)"System error - Cannot exec a shared library directly" },
        { ERR_EILSEQ, (char*)"System error - Illegal byte sequence" },
        { ERR_ERESTART, (char*)"System error - Interrupted system call should be restarted" },
        { ERR_ESTRPIPE, (char*)"System error - Streams pipe error" },
        { ERR_EUSERS, (char*)"System error - Too many users" },
        { ERR_ENOTSOCK, (char*)"System error - Socket operation on non-socket" },
        { ERR_EDESTADDRREQ, (char*)"System error - Destination address required" },
        { ERR_EMSGSIZE, (char*)"System error - Message too long" },
        { ERR_EPROTOTYPE, (char*)"System error - Protocol wrong type for socket" },
        { ERR_ENOPROTOOPT, (char*)"System error - Protocol not available" },
        { ERR_EPROTONOSUPPORT, (char*)"System error - Protocol not supported" },
        { ERR_ESOCKTNOSUPPORT, (char*)"System error - Socket type not supported" },
        { ERR_EOPNOTSUPP, (char*)"System error - Operation not supported on transport endpoint" },
        { ERR_EPFNOSUPPORT, (char*)"System error - Protocol family not supported" },
        { ERR_EAFNOSUPPORT, (char*)"System error - Address family not supported by protocol" },
        { ERR_EADDRINUSE, (char*)"System error - Address already in use" },
        { ERR_EADDRNOTAVAIL, (char*)"System error - Cannot assign requested address" },
        { ERR_ENETDOWN, (char*)"System error - Network is down" },
        { ERR_ENETUNREACH, (char*)"System error - Network is unreachable" },
        { ERR_ENETRESET, (char*)"System error - Network dropped connection because of reset" },
        { ERR_ECONNABORTED, (char*)"System error - Software caused connection abort" },
        { ERR_ECONNRESET, (char*)"System error - Connection reset by peer" },
        { ERR_ENOBUFS, (char*)"System error - No buffer space available" },
        { ERR_EISCONN, (char*)"System error - Transport endpoint is already connected" },
        { ERR_ENOTCONN, (char*)"System error - Transport endpoint is not connected" },
        { ERR_ESHUTDOWN, (char*)"System error - Cannot send after transport endpoint shutdown" },
        { ERR_ETOOMANYREFS, (char*)"System error - Too many references" },
        { ERR_ETIMEDOUT, (char*)"System error - Connection timed out" },
        { ERR_ECONNREFUSED, (char*)"System error - Connection refused" },
        { ERR_EHOSTDOWN, (char*)"System error - Host is down" },
        { ERR_EHOSTUNREACH, (char*)"System error - No route to host" },
        { ERR_EALREADY, (char*)"System error - Operation already in progress" },
        { ERR_EINPROGRESS, (char*)"System error - Operation now in progress" },
        { ERR_ESTALE, (char*)"System error - Stale NFS file handle" },
        { ERR_EUCLEAN, (char*)"System error - Structure needs cleaning" },
        { ERR_ENOTNAM, (char*)"System error - Not a XENIX named type file" },
        { ERR_ENAVAIL, (char*)"System error - No XENIX semaphores available" },
        { ERR_EISNAM, (char*)"System error - Is a named type file" },
        { ERR_EREMOTEIO, (char*)"System error - Remote I/O error" },
        { ERR_EDQUOT, (char*)"System error - Quota exceeded" },
        { ERR_ENOMEDIUM, (char*)"System error - No medium found" },
        { ERR_EMEDIUMTYPE, (char*)"System error - Wrong medium type" },
        { ERR_UNKNOWN_SYSTEM_ERROR, (char*)"Unknown (unmappable) system error" },
        { ERR_INVAL_SOCKET, (char*)"Invalid socket value" },
        { ERR_USER_ID_MISMATCH, (char*)"The user identities do not match." },
        { ERR_INVAL_PUBKEY, (char*)"Invalid public key" },
        { ERR_INVAL_ENTITY_RIGHT, (char*)"Invalid entity or right" },
        { ERR_TRANSACTION_ALIVE, (char*)"Transaction is still running" },
        { ERR_NOT_USER, (char*)"Entity is not a user" },
        { ERR_NOT_ROLE, (char*)"Entity is not a role" },
        { ERR_LIST_DUPLICATE_NOT_ALLOWED, (char*)"The list already contains an entry with that value" },
        { ERR_WF_HOLDER_SELECTION_METHOD_NOT_FOUND, (char*)"A specified holder selection method is invalid" },
        { ERR_ABORT_TRANSACTION, (char*)"Abort transaction" },
        { ERR_COMMIT_TRANSACTION, (char*)"Commit transaction" },
        { ERR_TRANSACTION_ABORTED, (char*)"Transaction aborted" },
        { ERR_TRANSACTION_COMMITED, (char*)"Transaction committed." },
        { ERR_READ_ONLY_SLAVE, (char*)"Object or entity is read only (its a slave embedded object)" },
        { ERR_DATA_NOT_PRESENT, (char*)"No data was present when it was expected." },
        { ERR_OBJECT_NOT_EMBEDDED, (char*)"The specified object is not embedded." },
        { ERR_INTERNAL_PROP_INVALID, (char*)"The internal property specified is invalid (never set)" },
        { ERR_INVALID_RUNTIME_ASSIGN, (char*)"The assign attempted is using mismatched types." },
        { ERR_INTERNAL_CLASS_NOTIMPL, (char*)"Internal class implementation could not be found." },
        { ERR_INVALID_COMPONENT, (char*)"The supplied component is invalid." },
        { ERR_RUNTIME_TYPE_MISMATCH, (char*)"A type mismatch has occurred." },
        { ERR_NOT_DEBUGGING, (char*)"A debug function was attempted on a non debug session." },
        { ERR_SRV_NOT_REGISTERED, (char*)"The local server is not registered with the registry." },
        { ERR_SERVERTICKET_FORMAT, (char*)"The supplied ticket is not in a valid format." },
        { ERR_INVAL_CACHE_REGISTER_ID, (char*)"Invalid cache register identity supplied." },
        { ERR_INVAL_CACHE_ITEM, (char*)"Invalid cache item (index or name)." },
        { ERR_SERVER_NOT_TRUSTED, (char*)"The signing server is not in our trusted list." },
        { ERR_WSAEINTR_10004, (char*)"A blocking operation was interrupted by a call to WSACancelBlockingCall (WIN32-10004)" },
        { ERR_WSAEBADF_10009, (char*)"The file handle supplied is not valid. (WIN32-10009)" },
        { ERR_WSAEACCES_10013, (char*)"An attempt was made to access a socket in a way forbidden by its access permissions. (WIN32-10013)" },
        { ERR_WSAEFAULT_10014, (char*)"The system detected an invalid pointer address in attempting to use a pointer argument in a call. (WIN32-10014)" },
        { ERR_WSAEINVAL_10022, (char*)"An invalid argument was supplied (WIN32-10022)" },
        { ERR_WSAEMFILE_10024, (char*)"Too many open sockets. (WIN32-10024)" },
        { ERR_WSAEWOULDBLOCK_10035, (char*)"A non-blocking socket operation could not be completed immediately. (WIN32-10035)" },
        { ERR_WSAEINPROGRESS_10036, (char*)"A blocking operation is currently executing. (WIN32-10036)" },
        { ERR_WSAEALREADY_10037, (char*)"An operation was attempted on a non-blocking socket that already had an operation in progress. (WIN32-10037)" },
        { ERR_WSAENOTSOCK_10038, (char*)"An operation was attempted on something that is not a socket. (WIN32-10038)" },
        { ERR_WSAEDESTADDRREQ_10039, (char*)"A required address was omitted from an operation on a socket. (WIN32-10039)" },
        { ERR_WSAEMSGSIZE_10040, (char*)"A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself. (WIN32-10040)" },
        { ERR_WSAEPROTOTYPE_10041, (char*)"A protocol was specified in the socket function call that does not support the semantics of the socket type requested. (WIN32-10041)" },
        { ERR_WSAENOPROTOOPT_10042, (char*)"An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call. (WIN32-10042)" },
        { ERR_WSAEPROTONOSUPPORT_10043, (char*)"The requested protocol has not been configured into the system, or no implementation for it exists. (WIN32-10043)" },
        { ERR_WSAESOCKTNOSUPPORT_10044, (char*)"The support for the specified socket type does not exist in this address family. (WIN32-10044)" },
        { ERR_WSAEOPNOTSUPP_10045, (char*)"The attempted operation is not supported for the type of object referenced. (WIN32-10045)" },
        { ERR_WSAEPFNOSUPPORT_10046, (char*)"The protocol family has not been configured into the system or no implementation for it exists. (WIN32-10046)" },
        { ERR_WSAEAFNOSUPPORT_10047, (char*)"An address incompatible with the requested protocol was used. (WIN32-10047)" },
        { ERR_WSAEADDRINUSE_10048, (char*)"Only one usage of each socket address (protocol/network address/port) is normally permitted. (WIN32-10048)" },
        { ERR_WSAEADDRNOTAVAIL_10049, (char*)"The requested address is not valid in its context. (WIN32-10049)" },
        { ERR_WSAENETDOWN_10050, (char*)"A socket operation encountered a dead network. (WIN32-10050)" },
        { ERR_WSAENETUNREACH_10051, (char*)"A socket operation was attempted to an unreachable network. (WIN32-10051)" },
        { ERR_WSAENETRESET_10052, (char*)"The connection has been broken due to keep-alive activity detecting a failure while the operation was in progress. (WIN32-10052)" },
        { ERR_WSAECONNABORTED_10053, (char*)"An established connection was aborted by the software in your host machine. (WIN32-10053)" },
        { ERR_WSAECONNRESET_10054, (char*)"An existing connection was forcibly closed by the remote host. (WIN32-10054)" },
        { ERR_WSAENOBUFS_10055, (char*)"An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full. (WIN32-10055)" },
        { ERR_WSAENOTCONN_10057, (char*)"A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied. (WIN32-10057)" },
        { ERR_WSAESHUTDOWN_10058, (char*)"A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call. (WIN32-10058)" },
        { ERR_WSAETOOMANYREFS_10059, (char*)"Too many references to some kernel object. (WIN32-10059)" },
        { ERR_WSAELOOP_10062, (char*)"Cannot translate name. (WIN32-10062)" },
        { ERR_WSAENAMETOOLONG_10063, (char*)"Name component or name was too long. (WIN32-10063)" },
        { ERR_WSAEHOSTDOWN_10064, (char*)"A socket operation failed because the destination host was down. (WIN32-10064)" },
        { ERR_WSAEHOSTUNREACH_10065, (char*)"A socket operation was attempted to an unreachable host. (WIN32-10065)" },
        { ERR_WSAENOTEMPTY_10066, (char*)"Cannot remove a directory that is not empty. (WIN32-10066)" },
        { ERR_WSAEPROCLIM_10067, (char*)"A Windows Sockets implementation may have a limit on the number of applications that may use it simultaneously. (WIN32-10067)" },
        { ERR_WSAEUSERS_10068, (char*)"Ran out of quota. (WIN32-10068)" },
        { ERR_WSAEDQUOT_10069, (char*)"Ran out of disk quota. (WIN32-10069)" },
        { ERR_WSAESTALE_10070, (char*)"File handle reference is no longer available. (WIN32-10070)" },
        { ERR_WSAEREMOTE_10071, (char*)"Item is not available locally. (WIN32-10071)" },
        { ERR_WSASYSNOTREADY_10091, (char*)"WSAStartup cannot function at this time because the underlying system it uses to provide network services is currently unavailable. (WIN32-10091)" },
        { ERR_WSAVERNOTSUPPORTED_10092, (char*)"The Windows Sockets version requested is not supported. (WIN32-10092)" },
        { ERR_WSANOTINITIALISED_10093, (char*)"Either the application has not called WSAStartup, or WSAStartup failed. (WIN32-10093)" },
        { ERR_WSAEISCONN, (char*)"The socket is already connected (WIN32-10056)." },
        { ERR_WSACONNREFUSED, (char*)"The connection was refused (WIN32-10061)." },
        { ERR_WSAETIMEDOUT_10060, (char*)"The connection timed out (WIN32-10060)" },
        { ERR_THREAD_RUNNING, (char*)"The thread is still running." },
        { ERR_THREAD_NOT_FOUND, (char*)"No such thread has been found." },
        { ERR_FOREIGN_OBJECT, (char*)"The object is foreign or a link." },
        { ERR_RULE_INVALID_SPACE, (char*)"The space supplied has no rules." },
        { ERR_RULE_NO_MATCH_CONTENT, (char*)"No matching rule for the container and mimetype was found." },
        { ERR_RULE_NO_MATCH_FOLDER, (char*)"No matching rule for the container was found." },
        { ERR_UPDATES_NON_AVAIL, (char*)"No new updates available" },
        { ERR_UPDATES_CREATE_FAIL, (char*)"Update creation failed." },
        { ERR_UPDATES_INVAL_OPSYS, (char*)"Invalid operating system" },
        { ERR_ALREADY_ROLE_MEMBER, (char*)"Server or user is already a member of the role" },
        { ERR_SSL_ERROR_ZERO_RETURN, (char*)"SSL_ERROR_ZERO_RETURN.The TLS/SSL connection has been closed." },
        { ERR_SSL_ERROR_WANT_READ, (char*)"SSL_ERROR_WANT_READ. The operation did not complete." },
        { ERR_SSL_ERROR_WANT_WRITE, (char*)"SSL_ERROR_WANT_WRITE. The operation did not complete." },
        { ERR_SSL_ERROR_WANT_CONNECT, (char*)"SSL_ERROR_WANT_CONNECT. The operation did not complete." },
        { ERR_SSL_ERROR_WANT_ACCEPT, (char*)"SSL_ERROR_WANT_ACCEPT. The operation did not complete." },
        { ERR_SSL_ERROR_WANT_X509_LOOKUP, (char*)"SSL_ERROR_WANT_X509_LOOKUP. The operation did not complete because an application callback set by SSL_CTX_set_client_cert_cb() has asked to be called again." },
        { ERR_SSL_ERROR_SYSCALL, (char*)"SSL_ERROR_SYSCALL. Some I/O error occurred. The OpenSSL error queue may contain more information." },
        { ERR_COULD_NOT_READ_ACL, (char*)"Could not read the object's ACL data." },
        { ERR_AUTH_MECH_NOT_ALLOWED, (char*)"Authentication mechanism not allowed." },
        { ERR_FRAMESTACK_LEVEL_EXCEEDED, (char*)"Run frame-stack level exceeded." },
        { ERR_SOFTRULES_DENIED_PLACEMENT, (char*)"An object of this class may not be placed under the specified parent." },
        { ERR_REGEX_FAILURE, (char*)"Regular expression failure." },
        { ERR_SERVER_PURGING, (char*)"Server is being purged" },
        { ERR_SERVER_PURGED, (char*)"Server has purged and is OK" },
        { ERR_SERVER_MUST_PURGE, (char*)"Server must purge before embedding etc" },
        { ERR_INVALID_IMAGE, (char*)"The supplied image is not valid" },
        { ERR_INVALID_FILE, (char*)"The supplied filename is invalid." },
        { ERR_NEW_SPACE_OFFLINE, (char*)"Cannot register a space with home server offline." },
        { ERR_SERVER_NOT_AVAILABLE, (char*)"Server not available." },
        { ERR_PARSER_ERROR, (char*)"Parser error" },
        { ERR_NOT_SERVICE, (char*)"The service is invalid (WIN32-1060)" },
        { ERR_SERVICE_NOT_ACTIVE_1062, (char*)"Service not started (WIN32-1062)" },
        { ERR_FAILED_SERVICE_CONTROLLER_CONNECT_1063, (char*)"The service process could not connect to the service controller (WIN32-1063)" },
        { ERR_NO_OF_ENVIRON, (char*)"No openFabric environment could be found." },
        { ERR_DELETE_IN_DESTRUCTOR, (char*)"Cannot delete myself in my own destructor." },
        { ERR_INVAL_CODE, (char*)"Invalid return code" },
        { ERR_INVAL_RESPONSE, (char*)"Invalid response" },
        { ERR_INVAL_TYPE, (char*)"Invalid type at runtime" },
        { ERR_PRINTS_ARG_COUNT, (char*)"PRINTS argument count mismatch" },
        { ERR_SPACERULE_NOT_FOUND, (char*)"Space rule not found" },
        { ERR_SERVER_TERMINATING, (char*)"Server is currently stopping" },
        { ERR_CLASS_IDNAME_MISMATCH, (char*)"Class identity/name mismatch" },
        { ERR_SYSCLM_CLASS_MISMATCH, (char*)"System/CLM class mismatch. Server out of date." },
        { ERR_SERVER_NAMEID_MISMATCH, (char*)"Registry server name/id mismatch" },
        { ERR_INVALID_ADMIN_FUNC, (char*)"Invalid administrative function" },
        { ERR_DEMOUSER_EXPIRED, (char*)"Demo user has expired" },
        { ERR_BUILDING, (char*)"A new search engine is building" },
        { ERR_NO_CURRENT_USER, (char*)"No current user." },
        { ERR_INCOMPAT_SERVER, (char*)"Local server version is not compatible with remote server." },
        { ERR_NEED_LOCK, (char*)"Object must be checked out to be modified." },
        { ERR_LOCK_HELD, (char*)"Another user has already checked out this object - try again later." },
        { ERR_LOCK_YOURS, (char*)"You have already checked out this object." },
        { ERR_XML_PARSE_XPATH, (char*)"Error parsing xpath." },
        { ERR_WSDL_CANNOT_FIND_WSDLPPITEM, (char*)"Cannot find specified WSDLPPItem" },
        { ERR_WSDL_CANNOT_FIND_TARGET_NAMESPACE, (char*)"Missing targetNamespace" },
        { ERR_BUFFER_TOO_SMALL, (char*)"The supplied buffer is too small" },
        { ERR_NONCE_EXPIRED, (char*)"The supplied nonce has expired" },
        { ERR_NOT_DICTIONARY_SERVER, (char*)"This server is not a dictionary server" },
        { ERR_HOME_DICTIONARY_MISMATCH, (char*)"Home and dictionary server mismatch" },
        { ERR_INVAL_ACCESS_FUNCTION, (char*)"Invalid access function" },
        { ERR_HOMESERVER_NOTAVAIL, (char*)"Home server could not be contacted." },
        { ERR_OBJECT_NAME_EMPTY, (char*)"Object name is empty" },
        { ERR_INVAL_ATTACHMENT, (char*)"Invalid (or empty) attachment" },
        { ERR_SSL_DECRYPT, (char*)"SSL decryption error" },
        { ERR_TOO_MANY_SITES, (char*)"Too many server sites" },
        { ERR_SSO_FAILED, (char*)"Single sign on failed" },
        { -1, (char*)"END" }
    };
    const char *descrip = 0;
    for ( ofuint32 x = 0; !descrip && names[x].index != -1; x++ )
        if ( names[x].index == (ofint32)enumValue )
        {
            descrip = names[x].name;
        }
    return descrip;
}


/* B */
const char *
translate_OFVALUE_TYPES2( ofuint32 enumValue )
{
    struct NAMEPAIR { ofint32 index; char *name; };
    NAMEPAIR names[] = {
        { typeInteger, (char*)"typeInteger" },
        { typeBoolean, (char*)"typeBoolean" },
        { typeString, (char*)"typeString" },
        { typeFloat, (char*)"typeFloat" },
        { typeOFDateTime, (char*)"typeOFDateTime" },
        { typeIdentity, (char*)"typeIdentity" },
        { typeBinary, (char*)"typeBinary" },
        { -1, (char*)"END" }
    };
    const char *val = 0;
    for ( ofuint32 x = 0; !val && names[x].index != -1; x++ )
        if ( names[x].index == (ofint32)enumValue )
        {
            val = names[x].name;;
        }
    return val;
}

/* B */
const char *
translate_OFERROR2( ofuint32 enumValue )
{
    struct NAMEPAIR { ofint32 index; char *name; };
    NAMEPAIR names[] = {
        { ERR_SUCCESS, (char*)"ERR_SUCCESS" },
        { ERR_INVAL_PROTMETH, (char*)"ERR_INVAL_PROTMETH" },
        { ERR_COMPILE_ERROR, (char*)"ERR_COMPILE_ERROR" },
        { ERR_INVAL_CLASS, (char*)"ERR_INVAL_CLASS" },
        { ERR_INVAL_OBJECT, (char*)"ERR_INVAL_OBJECT" },
        { ERR_PROXY_CONNECT, (char*)"ERR_PROXY_CONNECT" },
        { ERR_INT_EXEC_FAIL, (char*)"ERR_INT_EXEC_FAIL" },
        { ERR_ACCDEN, (char*)"ERR_ACCDEN" },
        { ERR_ENTITY_EXIST, (char*)"ERR_ENTITY_EXIST" },
        { ERR_ENTITY_NOTFOUND, (char*)"ERR_ENTITY_NOTFOUND" },
        { ERR_OBJSTORE_BUSY, (char*)"ERR_OBJSTORE_BUSY" },
        { ERR_NOTIMPL, (char*)"ERR_NOTIMPL" },
        { ERR_INT_DBMS, (char*)"ERR_INT_DBMS" },
        { ERR_AOM_INT, (char*)"ERR_AOM_INT" },
        { ERR_SUCCESS_WITH_INFO, (char*)"ERR_SUCCESS_WITH_INFO" },
        { ERR_INT_EXEC_ASSERT, (char*)"ERR_INT_EXEC_ASSERT" },
        { ERR_DIVIDE_BY_ZERO, (char*)"ERR_DIVIDE_BY_ZERO" },
        { ERR_EXEC_STACK_UNDER, (char*)"ERR_EXEC_STACK_UNDER" },
        { ERR_AOM_OBJECT_INT, (char*)"ERR_AOM_OBJECT_INT" },
        { ERR_EXEC_UNDEF_VAR, (char*)"ERR_EXEC_UNDEF_VAR" },
        { ERR_FILE_OPEN_ERR, (char*)"ERR_FILE_OPEN_ERR" },
        { ERR_LIB_NOSYM, (char*)"ERR_LIB_NOSYM" },
        { ERR_CLM_ERROR, (char*)"ERR_CLM_ERROR" },
        { ERR_METH_PARAM_COUNT, (char*)"ERR_METH_PARAM_COUNT" },
        { ERR_INVAL_METHOD, (char*)"ERR_INVAL_METHOD" },
        { ERR_INVAL_PROPERTY, (char*)"ERR_INVAL_PROPERTY" },
        { ERR_FIELD_NOTEXIST, (char*)"ERR_FIELD_NOTEXIST" },
        { ERR_INST_NOTEXIST, (char*)"ERR_INST_NOTEXIST" },
        { ERR_INST_ALREADY_RUN, (char*)"ERR_INST_ALREADY_RUN" },
        { ERR_INST_NOT_RUN, (char*)"ERR_INST_NOT_RUN" },
        { ERR_SYSTEM_INSTANCE, (char*)"ERR_SYSTEM_INSTANCE" },
        { ERR_LIB_NOCLASSLIST, (char*)"ERR_LIB_NOCLASSLIST" },
        { ERR_LIB_ERROR, (char*)"ERR_LIB_ERROR" },
        { ERR_LIB_NOT_CREATE_CLASS, (char*)"ERR_LIB_NOT_CREATE_CLASS" },
        { ERR_OBJECT_HAS_CHILDREN, (char*)"ERR_OBJECT_HAS_CHILDREN" },
        { ERR_CLASS_HAS_CHILDREN, (char*)"ERR_CLASS_HAS_CHILDREN" },
        { ERR_CANT_DESTROY_ROOT, (char*)"ERR_CANT_DESTROY_ROOT" },
        { ERR_CANT_DESTROY_SYSTEM_OBJECT, (char*)"ERR_CANT_DESTROY_SYSTEM_OBJECT" },
        { ERR_CANT_DESTROY_SYSTEM_CLASS, (char*)"ERR_CANT_DESTROY_SYSTEM_CLASS" },
        { ERR_INVAL_LIB_ALIAS, (char*)"ERR_INVAL_LIB_ALIAS" },
        { ERR_INVAL_SUB_FUNCTION, (char*)"ERR_INVAL_SUB_FUNCTION" },
        { ERR_INVAL_COLONEL_FUNCTION, (char*)"ERR_INVAL_COLONEL_FUNCTION" },
        { ERR_INVAL_DATA_ID, (char*)"ERR_INVAL_DATA_ID" },
        { ERR_ELVIS_ERROR, (char*)"ERR_ELVIS_ERROR" },
        { ERR_INVAL_USERPASS, (char*)"ERR_INVAL_USERPASS" },
        { ERR_SESSION_INVALID, (char*)"ERR_SESSION_INVALID" },
        { ERR_NETWORK_FAILED, (char*)"ERR_NETWORK_FAILED" },
        { ERR_DEADLOCK_ABORT, (char*)"ERR_DEADLOCK_ABORT" },
        { ERR_INVAL_PARENT, (char*)"ERR_INVAL_PARENT" },
        { ERR_INVAL_NAME, (char*)"ERR_INVAL_NAME" },
        { ERR_INVAL_FILE_HANDLE, (char*)"ERR_INVAL_FILE_HANDLE" },
        { ERR_OFSOCKET_ERROR, (char*)"ERR_OFSOCKET_ERROR" },
        { ERR_INT_OFOR, (char*)"ERR_INT_OFOR" },
        { ERR_CLM_NO_OFAP_MSG, (char*)"ERR_CLM_NO_OFAP_MSG" },
        { ERR_CLM_XSL_TRANSFORM_FAILED, (char*)"ERR_CLM_XSL_TRANSFORM_FAILED" },
        { ERR_SOCKET_TIMEOUT, (char*)"ERR_SOCKET_TIMEOUT" },
        { ERR_UNLOCATABLE, (char*)"ERR_UNLOCATABLE" },
        { ERR_LDAP_CONNECTION, (char*)"ERR_LDAP_CONNECTION" },
        { ERR_LDAP_ENTRY, (char*)"ERR_LDAP_ENTRY" },
        { ERR_LDAP_ATTRIBUTE, (char*)"ERR_LDAP_ATTRIBUTE" },
        { ERR_LDAP_ADD, (char*)"ERR_LDAP_ADD" },
        { ERR_LDAP_DELETE, (char*)"ERR_LDAP_DELETE" },
        { ERR_LDAP_MODIFY, (char*)"ERR_LDAP_MODIFY" },
        { ERR_NEW_ID, (char*)"ERR_NEW_ID" },
        { ERR_AUTHENTICATION_FAILURE, (char*)"ERR_AUTHENTICATION_FAILURE" },
        { ERR_SERIAL_FILE, (char*)"ERR_SERIAL_FILE" },
        { ERR_MEMORY_ALLOCATION, (char*)"ERR_MEMORY_ALLOCATION" },
        { ERR_CERT_REQUEST, (char*)"ERR_CERT_REQUEST" },
        { ERR_CERT_REQUEST_FORMAT, (char*)"ERR_CERT_REQUEST_FORMAT" },
        { ERR_EMAIL_FORMAT, (char*)"ERR_EMAIL_FORMAT" },
        { ERR_ILLEGAL_CHARACTERS, (char*)"ERR_ILLEGAL_CHARACTERS" },
        { ERR_REQUIRED_FIELD_MISSING, (char*)"ERR_REQUIRED_FIELD_MISSING" },
        { ERR_MATCHING_FIELD_MISSING, (char*)"ERR_MATCHING_FIELD_MISSING" },
        { ERR_CA_FIELD_MISSING, (char*)"ERR_CA_FIELD_MISSING" },
        { ERR_MATCHING_FIELD, (char*)"ERR_MATCHING_FIELD" },
        { ERR_INVALID_TYPE_IN_POLICY, (char*)"ERR_INVALID_TYPE_IN_POLICY" },
        { ERR_USER_NAME_EXISTS, (char*)"ERR_USER_NAME_EXISTS" },
        { ERR_USER_NAME_DOES_NOT_EXIST, (char*)"ERR_USER_NAME_DOES_NOT_EXIST" },
        { ERR_USER_NAME_REQUIRED, (char*)"ERR_USER_NAME_REQUIRED" },
        { ERR_ID_EXISTS, (char*)"ERR_ID_EXISTS" },
        { ERR_ID_DOES_NOT_EXIST, (char*)"ERR_ID_DOES_NOT_EXIST" },
        { ERR_INVALID_CERT, (char*)"ERR_INVALID_CERT" },
        { ERR_SIGNING_FAILED, (char*)"ERR_SIGNING_FAILED" },
        { ERR_CERT_EXPIRED, (char*)"ERR_CERT_EXPIRED" },
        { ERR_CERT_REVOKED, (char*)"ERR_CERT_REVOKED" },
        { ERR_CERT_REQUIRED, (char*)"ERR_CERT_REQUIRED" },
        { ERR_INVALID_SIGNATURE, (char*)"ERR_INVALID_SIGNATURE" },
        { ERR_REF_COUNT_CHANGE, (char*)"ERR_REF_COUNT_CHANGE" },
        { ERR_CONNECTION_ERROR, (char*)"ERR_CONNECTION_ERROR" },
        { ERR_NOT_AUTHENTICATED, (char*)"ERR_NOT_AUTHENTICATED" },
        { ERR_REGISTRY_INFO, (char*)"ERR_REGISTRY_INFO" },
        { ERR_NO_CONTACT_REGISTRY, (char*)"ERR_NO_CONTACT_REGISTRY" },
        { ERR_NO_CONTACT_SENTINEL, (char*)"ERR_NO_CONTACT_SENTINEL" },
        { ERR_NO_CONTACT_ACCESS, (char*)"ERR_NO_CONTACT_ACCESS" },
        { ERR_NO_CONTACT_COMPONENT, (char*)"ERR_NO_CONTACT_COMPONENT" },
        { ERR_REGISTRY_INVAL_SERVER, (char*)"ERR_REGISTRY_INVAL_SERVER" },
        { ERR_REGISTRY_INVAL_USER, (char*)"ERR_REGISTRY_INVAL_USER" },
        { ERR_NAME_NOT_SET, (char*)"ERR_NAME_NOT_SET" },
        { ERR_INVALID_TOKEN, (char*)"ERR_INVALID_TOKEN" },
        { ERR_ILLEGAL_ACTION, (char*)"ERR_ILLEGAL_ACTION" },
        { ERR_ILLEGAL_FIELD, (char*)"ERR_ILLEGAL_FIELD" },
        { ERR_PRIVATE_KEY, (char*)"ERR_PRIVATE_KEY" },
        { ERR_WRITE_PRIVATE_KEY, (char*)"ERR_WRITE_PRIVATE_KEY" },
        { ERR_SIGN_REQ, (char*)"ERR_SIGN_REQ" },
        { ERR_WRITE_REQ, (char*)"ERR_WRITE_REQ" },
        { ERR_REQ_VERSION, (char*)"ERR_REQ_VERSION" },
        { ERR_ADD_SUBJECT_FIELD, (char*)"ERR_ADD_SUBJECT_FIELD" },
        { ERR_WRITE_CERT, (char*)"ERR_WRITE_CERT" },
        { ERR_CERT_OR_PRIV_KEY, (char*)"ERR_CERT_OR_PRIV_KEY" },
        { ERR_REPLACE_NAME, (char*)"ERR_REPLACE_NAME" },
        { ERR_ADDRESS, (char*)"ERR_ADDRESS" },
        { ERR_IP_ADDRESS, (char*)"ERR_IP_ADDRESS" },
        { ERR_CANNOT_ADD_EXTENSION, (char*)"ERR_CANNOT_ADD_EXTENSION" },
        { ERR_AUTHENTICATION_REQUIRED, (char*)"ERR_AUTHENTICATION_REQUIRED" },
        { ERR_VERIFY_FAILED, (char*)"ERR_VERIFY_FAILED" },
        { ERR_RESPONDER_NOT_EXISTS, (char*)"ERR_RESPONDER_NOT_EXISTS" },
        { ERR_INVALID_RESP_METHOD, (char*)"ERR_INVALID_RESP_METHOD" },
        { ERR_CONFIG_FILE, (char*)"ERR_CONFIG_FILE" },
        { ERR_SSL_CONNECT, (char*)"ERR_SSL_CONNECT" },
        { ERR_SSL_CERT, (char*)"ERR_SSL_CERT" },
        { ERR_SSL_PRIVKEY, (char*)"ERR_SSL_PRIVKEY" },
        { ERR_SSL_CERTKEY_MISMATCH, (char*)"ERR_SSL_CERTKEY_MISMATCH" },
        { ERR_SSL_SERIALFILE_ERROR, (char*)"ERR_SSL_SERIALFILE_ERROR" },
        { ERR_SCHEDULER_INVAL_TASK, (char*)"ERR_SCHEDULER_INVAL_TASK" },
        { ERR_SSL_CONNECTION_REQUIRED, (char*)"ERR_SSL_CONNECTION_REQUIRED" },
        { ERR_REG_NO_ID_LEFT, (char*)"ERR_REG_NO_ID_LEFT" },
        { ERR_INVAL_LIC_FORMAT, (char*)"ERR_INVAL_LIC_FORMAT" },
        { ERR_COMMIT_INCOMPLETE, (char*)"ERR_COMMIT_INCOMPLETE" },
        { ERR_WAIT_FOR, (char*)"ERR_WAIT_FOR" },
        { ERR_NOT_LOCAL, (char*)"ERR_NOT_LOCAL" },
        { ERR_SICK, (char*)"ERR_SICK" },
        { ERR_INVAL_REQUEST, (char*)"ERR_INVAL_REQUEST" },
        { ERR_BAD_LINK, (char*)"ERR_BAD_LINK" },
        { ERR_INVAL_TRANSACTION, (char*)"ERR_INVAL_TRANSACTION" },
        { ERR_LOCAL_LINK, (char*)"ERR_LOCAL_LINK" },
        { ERR_PROXY_INTERNAL, (char*)"ERR_PROXY_INTERNAL" },
        { ERR_EMPTY_ACL, (char*)"ERR_EMPTY_ACL" },
        { ERR_INVAL_EXEC_CONTEXT, (char*)"ERR_INVAL_EXEC_CONTEXT" },
        { ERR_TRANSACTION_DEAD, (char*)"ERR_TRANSACTION_DEAD" },
        { ERR_UNKNOWN_ACLMAN_FUNC, (char*)"ERR_UNKNOWN_ACLMAN_FUNC" },
        { ERR_XML_ERROR_PARSING_INPUT_FILE, (char*)"ERR_XML_ERROR_PARSING_INPUT_FILE" },
        { ERR_XML_ERROR_PARSING_WSDL_FILE, (char*)"ERR_XML_ERROR_PARSING_WSDL_FILE" },
        { ERR_XML_ERROR_PARSING_WSDL_IMPORT_FILE, (char*)"ERR_XML_ERROR_PARSING_WSDL_IMPORT_FILE" },
        { ERR_XML_ERROR_PARSING_XSLT_STYLESHEET, (char*)"ERR_XML_ERROR_PARSING_XSLT_STYLESHEET" },
        { ERR_XML_CANNOT_RETRIEVE_WSDL_FILE, (char*)"ERR_XML_CANNOT_RETRIEVE_WSDL_FILE" },
        { ERR_XSLT_TRANSFORM, (char*)"ERR_XSLT_TRANSFORM" },
        { ERR_XSLT_TRANSFORM_RELATED, (char*)"ERR_XSLT_TRANSFORM_RELATED" },
        { ERR_SOAP_ERROR_LOADING_OBJECT, (char*)"ERR_SOAP_ERROR_LOADING_OBJECT" },
        { ERR_WSDL_ERROR_PARSING_COMPLEX_TYPES, (char*)"ERR_WSDL_ERROR_PARSING_COMPLEX_TYPES" },
        { ERR_WSDL_CXT_COMPILE_FAILED, (char*)"ERR_WSDL_CXT_COMPILE_FAILED" },
        { ERR_WSDL_CLASS_COMPILE_FAILED, (char*)"ERR_WSDL_CLASS_COMPILE_FAILED" },
        { ERR_WSDL_CANNOT_CREATE_CLASS, (char*)"ERR_WSDL_CANNOT_CREATE_CLASS" },
        { ERR_WSDL_CANNOT_FIND_DEFAULT_NAMESPACE_IN_WSDL_FILE, (char*)"ERR_WSDL_CANNOT_FIND_DEFAULT_NAMESPACE_IN_WSDL_FILE" },
        { ERR_WSDL_CANNOT_FIND_XMLSCHEMA_NAMESPACE_IN_WSDL_FILE, (char*)"ERR_WSDL_CANNOT_FIND_XMLSCHEMA_NAMESPACE_IN_WSDL_FILE" },
        { ERR_WSDL_CANNOT_FIND_DEFAULT_NAMESPACE_IN_WSDL_IMPORT_FILE, (char*)"ERR_WSDL_CANNOT_FIND_DEFAULT_NAMESPACE_IN_WSDL_IMPORT_FILE" },
        { ERR_WSDL_CANNOT_FIND_XMLSCHEMA_NAMESPACE_IN_WSDL_IMPORT_FILE, (char*)"ERR_WSDL_CANNOT_FIND_XMLSCHEMA_NAMESPACE_IN_WSDL_IMPORT_FILE" },
        { ERR_WSDL_CANNOT_FIND_NAMESPACE_IN_WSDL_IMPORT_TAG, (char*)"ERR_WSDL_CANNOT_FIND_NAMESPACE_IN_WSDL_IMPORT_TAG" },
        { ERR_WSDL_CANNOT_FIND_LOCATION_IN_WSDL_IMPORT_TAG, (char*)"ERR_WSDL_CANNOT_FIND_LOCATION_IN_WSDL_IMPORT_TAG" },
        { ERR_WSDL_ERROR_ADDING_CHILD_NODE_FROM_WSDL_IMPORT_FILE, (char*)"ERR_WSDL_ERROR_ADDING_CHILD_NODE_FROM_WSDL_IMPORT_FILE" },
        { ERR_WSDL_NOTHING_TO_IMPORT_FROM_WSDL_IMPORT_FILE, (char*)"ERR_WSDL_NOTHING_TO_IMPORT_FROM_WSDL_IMPORT_FILE" },
        { ERR_WSDL_CANNOT_FIND_SERVICE_NAME, (char*)"ERR_WSDL_CANNOT_FIND_SERVICE_NAME" },
        { ERR_WSDL_CANNOT_FIND_ANY_PORTS, (char*)"ERR_WSDL_CANNOT_FIND_ANY_PORTS" },
        { ERR_WSDL_CANNOT_FIND_BINDING_ATTRIBUTE_FOR_PORT, (char*)"ERR_WSDL_CANNOT_FIND_BINDING_ATTRIBUTE_FOR_PORT" },
        { ERR_WSDL_CANNOT_FIND_LOCATION_FOR_PORT, (char*)"ERR_WSDL_CANNOT_FIND_LOCATION_FOR_PORT" },
        { ERR_WSDL_CANNOT_FIND_BINDING_TYPE, (char*)"ERR_WSDL_CANNOT_FIND_BINDING_TYPE" },
        { ERR_WSDL_CANNOT_FIND_BINDING_OPERATIONS, (char*)"ERR_WSDL_CANNOT_FIND_BINDING_OPERATIONS" },
        { ERR_WSDL_MISSING_SOAP_ACTION, (char*)"ERR_WSDL_MISSING_SOAP_ACTION" },
        { ERR_WSDL_CANNOT_FIND_PORTTYPE_OPERATIONS, (char*)"ERR_WSDL_CANNOT_FIND_PORTTYPE_OPERATIONS" },
        { ERR_WSDL_MISSING_ATTRIBUTE_FOR_COMPLEX_TYPE, (char*)"ERR_WSDL_MISSING_ATTRIBUTE_FOR_COMPLEX_TYPE" },
        { ERR_WSDL_ERROR_ADDING_CONTAINER_CLASS, (char*)"ERR_WSDL_ERROR_ADDING_CONTAINER_CLASS" },
        { ERR_WSDL_ERROR_ADDING_BASE_CLASS, (char*)"ERR_WSDL_ERROR_ADDING_BASE_CLASS" },
        { ERR_WSDL_ERROR_ADDING_COMPLEXTYPE_CLASS, (char*)"ERR_WSDL_ERROR_ADDING_COMPLEXTYPE_CLASS" },
        { ERR_WSDL_ERROR_PARSING_COMPLEXTYPE_NAMES_FILE, (char*)"ERR_WSDL_ERROR_PARSING_COMPLEXTYPE_NAMES_FILE" },
        { ERR_WSDL_ERROR_PARSING_COMPLEXTYPE_SLICER_FILE, (char*)"ERR_WSDL_ERROR_PARSING_COMPLEXTYPE_SLICER_FILE" },
        { ERR_WSDL_FAILED_TO_RESOLVE_METHOD_RETURN_COMPLEXTYPE_REFERENCE, (char*)"ERR_WSDL_FAILED_TO_RESOLVE_METHOD_RETURN_COMPLEXTYPE_REFERENCE" },
        { ERR_WSDL_FAILED_TO_RESOLVE_PARAMETER_COMPLEXTYPE_REFERENCE, (char*)"ERR_WSDL_FAILED_TO_RESOLVE_PARAMETER_COMPLEXTYPE_REFERENCE" },
        { ERR_WSDL_FAILED_TO_RESOLVE_METHOD, (char*)"ERR_WSDL_FAILED_TO_RESOLVE_METHOD" },
        { ERR_WSDL_FAILED_TO_RESOLVE_PROPERTY_COMPLEXTYPE_REFERENCE, (char*)"ERR_WSDL_FAILED_TO_RESOLVE_PROPERTY_COMPLEXTYPE_REFERENCE" },
        { ERR_WSDL_XSLT_TRANSFORM_FAILED, (char*)"ERR_WSDL_XSLT_TRANSFORM_FAILED" },
        { ERR_WSDL_FAILED_TO_DETERMINE_TYPE_OF_WSDL_FILE, (char*)"ERR_WSDL_FAILED_TO_DETERMINE_TYPE_OF_WSDL_FILE" },
        { ERR_WSDL_FAILED_TO_OBTAIN_CLSGUARD, (char*)"ERR_WSDL_FAILED_TO_OBTAIN_CLSGUARD" },
        { ERR_WSDL_ERROR_PARSING_WSDLCXTPREPROCESS_SLICER_FILE, (char*)"ERR_WSDL_ERROR_PARSING_WSDLCXTPREPROCESS_SLICER_FILE" },
        { ERR_WSDL_ERROR_PARSING_WSDLPREPROCESS_SLICER_FILE, (char*)"ERR_WSDL_ERROR_PARSING_WSDLPREPROCESS_SLICER_FILE" },
        { ERR_WSDL_NO_URI, (char*)"ERR_WSDL_NO_URI" },
        { ERR_ERROR_APPLYING_WSDL_ANALYSE_STYLESHEET, (char*)"ERR_ERROR_APPLYING_WSDL_ANALYSE_STYLESHEET" },
        { ERR_ERROR_APPLYING_WSDL_CXT_ANALYSE_STYLESHEET, (char*)"ERR_ERROR_APPLYING_WSDL_CXT_ANALYSE_STYLESHEET" },
        { ERR_ERROR_APPLYING_WSDL_CXT_SLICER_STYLESHEET, (char*)"ERR_ERROR_APPLYING_WSDL_CXT_SLICER_STYLESHEET" },
        { ERR_ERROR_APPLYING_WSDL_IMPORTS_ANALYSE_STYLESHEET, (char*)"ERR_ERROR_APPLYING_WSDL_IMPORTS_ANALYSE_STYLESHEET" },
        { ERR_ERROR_APPLYING_WSDL_CXT_NAMES_STYLESHEET, (char*)"ERR_ERROR_APPLYING_WSDL_CXT_NAMES_STYLESHEET" },
        { ERR_ERROR_APPLYING_PREPROCESS_STYLESHEET, (char*)"ERR_ERROR_APPLYING_PREPROCESS_STYLESHEET" },
        { ERR_ERROR_APPLYING_CXT_PREPROCESS_STYLESHEET, (char*)"ERR_ERROR_APPLYING_CXT_PREPROCESS_STYLESHEET" },
        { ERR_ACCESS_TOKEN_NOT_FOUND, (char*)"ERR_ACCESS_TOKEN_NOT_FOUND" },
        { ERR_WSDL_CANNOT_RE_ADD_CLASS, (char*)"ERR_WSDL_CANNOT_RE_ADD_CLASS" },
        { ERR_SOAP_CALL_TO_REMOTE_SERVER_FAILED, (char*)"ERR_SOAP_CALL_TO_REMOTE_SERVER_FAILED" },
        { ERR_SOAP_REMOTE_SERVER_RETURNED_INVALID_RESPONSE, (char*)"ERR_SOAP_REMOTE_SERVER_RETURNED_INVALID_RESPONSE" },
        { ERR_SOAP_FAILED_TO_FIND_OPERATION_NAMESPACE, (char*)"ERR_SOAP_FAILED_TO_FIND_OPERATION_NAMESPACE" },
        { ERR_SOAP_FAILED_TO_PARSE_RESPONSE, (char*)"ERR_SOAP_FAILED_TO_PARSE_RESPONSE" },
        { ERR_SOAP_FAILED_TO_RESOLVE_OPERATION_NAME, (char*)"ERR_SOAP_FAILED_TO_RESOLVE_OPERATION_NAME" },
        { ERR_SOAP_FAILED_TO_FIND_SOAP_ACTION, (char*)"ERR_SOAP_FAILED_TO_FIND_SOAP_ACTION" },
        { ERR_SOAP_FAILED_TO_FIND_LOCATION, (char*)"ERR_SOAP_FAILED_TO_FIND_LOCATION" },
        { ERR_SOAP_FAILED_TO_FIND_NAMESPACE_FOR_OPERATION, (char*)"ERR_SOAP_FAILED_TO_FIND_NAMESPACE_FOR_OPERATION" },
        { ERR_SOAP_FAILED_TO_FIND_RESPONSE_RETURN_VALUE, (char*)"ERR_SOAP_FAILED_TO_FIND_RESPONSE_RETURN_VALUE" },
        { ERR_SOAP_SOAP_FAULT_RETURNED, (char*)"ERR_SOAP_SOAP_FAULT_RETURNED" },
        { ERR_TOKEN_EXPIRED, (char*)"ERR_TOKEN_EXPIRED" },
        { ERR_ADDRESS_INVALID, (char*)"ERR_ADDRESS_INVALID" },
        { ERR_INVAL_QUEUE, (char*)"ERR_INVAL_QUEUE" },
        { ERR_NO_MESSAGES, (char*)"ERR_NO_MESSAGES" },
        { ERR_INVAL_LISTENER, (char*)"ERR_INVAL_LISTENER" },
        { ERR_ALREADY_REGISTERED, (char*)"ERR_ALREADY_REGISTERED" },
        { ERR_INVAL_EVENT, (char*)"ERR_INVAL_EVENT" },
        { ERR_OUT_OF_RANGE, (char*)"ERR_OUT_OF_RANGE" },
        { ERR_INVAL_FORMAT, (char*)"ERR_INVAL_FORMAT" },
        { ERR_OFAP_MSG_MALFORMED, (char*)"ERR_OFAP_MSG_MALFORMED" },
        { ERR_INVALID_INDEX, (char*)"ERR_INVALID_INDEX" },
        { ERR_EPERM, (char*)"ERR_EPERM" },
        { ERR_ENOENT, (char*)"ERR_ENOENT" },
        { ERR_ESRCH, (char*)"ERR_ESRCH" },
        { ERR_EINTR, (char*)"ERR_EINTR" },
        { ERR_EIO, (char*)"ERR_EIO" },
        { ERR_ENXIO, (char*)"ERR_ENXIO" },
        { ERR_E2BIG, (char*)"ERR_E2BIG" },
        { ERR_ENOEXEC, (char*)"ERR_ENOEXEC" },
        { ERR_EBADF, (char*)"ERR_EBADF" },
        { ERR_ECHILD, (char*)"ERR_ECHILD" },
        { ERR_EAGAIN, (char*)"ERR_EAGAIN" },
        { ERR_ENOMEM, (char*)"ERR_ENOMEM" },
        { ERR_EACCES, (char*)"ERR_EACCES" },
        { ERR_EFAULT, (char*)"ERR_EFAULT" },
        { ERR_ENOTBLK, (char*)"ERR_ENOTBLK" },
        { ERR_EBUSY, (char*)"ERR_EBUSY" },
        { ERR_EEXIST, (char*)"ERR_EEXIST" },
        { ERR_EXDEV, (char*)"ERR_EXDEV" },
        { ERR_ENODEV, (char*)"ERR_ENODEV" },
        { ERR_ENOTDIR, (char*)"ERR_ENOTDIR" },
        { ERR_EISDIR, (char*)"ERR_EISDIR" },
        { ERR_EINVAL, (char*)"ERR_EINVAL" },
        { ERR_ENFILE, (char*)"ERR_ENFILE" },
        { ERR_EMFILE, (char*)"ERR_EMFILE" },
        { ERR_ENOTTY, (char*)"ERR_ENOTTY" },
        { ERR_ETXTBSY, (char*)"ERR_ETXTBSY" },
        { ERR_EFBIG, (char*)"ERR_EFBIG" },
        { ERR_ENOSPC, (char*)"ERR_ENOSPC" },
        { ERR_ESPIPE, (char*)"ERR_ESPIPE" },
        { ERR_EROFS, (char*)"ERR_EROFS" },
        { ERR_EMLINK, (char*)"ERR_EMLINK" },
        { ERR_EPIPE, (char*)"ERR_EPIPE" },
        { ERR_EDOM, (char*)"ERR_EDOM" },
        { ERR_ERANGE, (char*)"ERR_ERANGE" },
        { ERR_EDEADLK, (char*)"ERR_EDEADLK" },
        { ERR_ENAMETOOLONG, (char*)"ERR_ENAMETOOLONG" },
        { ERR_ENOLCK, (char*)"ERR_ENOLCK" },
        { ERR_ENOSYS, (char*)"ERR_ENOSYS" },
        { ERR_ENOTEMPTY, (char*)"ERR_ENOTEMPTY" },
        { ERR_ELOOP, (char*)"ERR_ELOOP" },
        { ERR_EWOULDBLOCK, (char*)"ERR_EWOULDBLOCK" },
        { ERR_ENOMSG, (char*)"ERR_ENOMSG" },
        { ERR_EIDRM, (char*)"ERR_EIDRM" },
        { ERR_ECHRNG, (char*)"ERR_ECHRNG" },
        { ERR_EL2NSYNC, (char*)"ERR_EL2NSYNC" },
        { ERR_EL3HLT, (char*)"ERR_EL3HLT" },
        { ERR_EL3RST, (char*)"ERR_EL3RST" },
        { ERR_ELNRNG, (char*)"ERR_ELNRNG" },
        { ERR_EUNATCH, (char*)"ERR_EUNATCH" },
        { ERR_ENOCSI, (char*)"ERR_ENOCSI" },
        { ERR_EL2HLT, (char*)"ERR_EL2HLT" },
        { ERR_EBADE, (char*)"ERR_EBADE" },
        { ERR_EBADR, (char*)"ERR_EBADR" },
        { ERR_EXFULL, (char*)"ERR_EXFULL" },
        { ERR_ENOANO, (char*)"ERR_ENOANO" },
        { ERR_EBADRQC, (char*)"ERR_EBADRQC" },
        { ERR_EBADSLT, (char*)"ERR_EBADSLT" },
        { ERR_EDEADLOCK, (char*)"ERR_EDEADLOCK" },
        { ERR_EBFONT, (char*)"ERR_EBFONT" },
        { ERR_ENOSTR, (char*)"ERR_ENOSTR" },
        { ERR_ENODATA, (char*)"ERR_ENODATA" },
        { ERR_ETIME, (char*)"ERR_ETIME" },
        { ERR_ENOSR, (char*)"ERR_ENOSR" },
        { ERR_ENONET, (char*)"ERR_ENONET" },
        { ERR_ENOPKG, (char*)"ERR_ENOPKG" },
        { ERR_EREMOTE, (char*)"ERR_EREMOTE" },
        { ERR_ENOLINK, (char*)"ERR_ENOLINK" },
        { ERR_EADV, (char*)"ERR_EADV" },
        { ERR_ESRMNT, (char*)"ERR_ESRMNT" },
        { ERR_ECOMM, (char*)"ERR_ECOMM" },
        { ERR_EPROTO, (char*)"ERR_EPROTO" },
        { ERR_EMULTIHOP, (char*)"ERR_EMULTIHOP" },
        { ERR_EDOTDOT, (char*)"ERR_EDOTDOT" },
        { ERR_EBADMSG, (char*)"ERR_EBADMSG" },
        { ERR_EOVERFLOW, (char*)"ERR_EOVERFLOW" },
        { ERR_ENOTUNIQ, (char*)"ERR_ENOTUNIQ" },
        { ERR_EBADFD, (char*)"ERR_EBADFD" },
        { ERR_EREMCHG, (char*)"ERR_EREMCHG" },
        { ERR_ELIBACC, (char*)"ERR_ELIBACC" },
        { ERR_ELIBBAD, (char*)"ERR_ELIBBAD" },
        { ERR_ELIBSCN, (char*)"ERR_ELIBSCN" },
        { ERR_ELIBMAX, (char*)"ERR_ELIBMAX" },
        { ERR_ELIBEXEC, (char*)"ERR_ELIBEXEC" },
        { ERR_EILSEQ, (char*)"ERR_EILSEQ" },
        { ERR_ERESTART, (char*)"ERR_ERESTART" },
        { ERR_ESTRPIPE, (char*)"ERR_ESTRPIPE" },
        { ERR_EUSERS, (char*)"ERR_EUSERS" },
        { ERR_ENOTSOCK, (char*)"ERR_ENOTSOCK" },
        { ERR_EDESTADDRREQ, (char*)"ERR_EDESTADDRREQ" },
        { ERR_EMSGSIZE, (char*)"ERR_EMSGSIZE" },
        { ERR_EPROTOTYPE, (char*)"ERR_EPROTOTYPE" },
        { ERR_ENOPROTOOPT, (char*)"ERR_ENOPROTOOPT" },
        { ERR_EPROTONOSUPPORT, (char*)"ERR_EPROTONOSUPPORT" },
        { ERR_ESOCKTNOSUPPORT, (char*)"ERR_ESOCKTNOSUPPORT" },
        { ERR_EOPNOTSUPP, (char*)"ERR_EOPNOTSUPP" },
        { ERR_EPFNOSUPPORT, (char*)"ERR_EPFNOSUPPORT" },
        { ERR_EAFNOSUPPORT, (char*)"ERR_EAFNOSUPPORT" },
        { ERR_EADDRINUSE, (char*)"ERR_EADDRINUSE" },
        { ERR_EADDRNOTAVAIL, (char*)"ERR_EADDRNOTAVAIL" },
        { ERR_ENETDOWN, (char*)"ERR_ENETDOWN" },
        { ERR_ENETUNREACH, (char*)"ERR_ENETUNREACH" },
        { ERR_ENETRESET, (char*)"ERR_ENETRESET" },
        { ERR_ECONNABORTED, (char*)"ERR_ECONNABORTED" },
        { ERR_ECONNRESET, (char*)"ERR_ECONNRESET" },
        { ERR_ENOBUFS, (char*)"ERR_ENOBUFS" },
        { ERR_EISCONN, (char*)"ERR_EISCONN" },
        { ERR_ENOTCONN, (char*)"ERR_ENOTCONN" },
        { ERR_ESHUTDOWN, (char*)"ERR_ESHUTDOWN" },
        { ERR_ETOOMANYREFS, (char*)"ERR_ETOOMANYREFS" },
        { ERR_ETIMEDOUT, (char*)"ERR_ETIMEDOUT" },
        { ERR_ECONNREFUSED, (char*)"ERR_ECONNREFUSED" },
        { ERR_EHOSTDOWN, (char*)"ERR_EHOSTDOWN" },
        { ERR_EHOSTUNREACH, (char*)"ERR_EHOSTUNREACH" },
        { ERR_EALREADY, (char*)"ERR_EALREADY" },
        { ERR_EINPROGRESS, (char*)"ERR_EINPROGRESS" },
        { ERR_ESTALE, (char*)"ERR_ESTALE" },
        { ERR_EUCLEAN, (char*)"ERR_EUCLEAN" },
        { ERR_ENOTNAM, (char*)"ERR_ENOTNAM" },
        { ERR_ENAVAIL, (char*)"ERR_ENAVAIL" },
        { ERR_EISNAM, (char*)"ERR_EISNAM" },
        { ERR_EREMOTEIO, (char*)"ERR_EREMOTEIO" },
        { ERR_EDQUOT, (char*)"ERR_EDQUOT" },
        { ERR_ENOMEDIUM, (char*)"ERR_ENOMEDIUM" },
        { ERR_EMEDIUMTYPE, (char*)"ERR_EMEDIUMTYPE" },
        { ERR_UNKNOWN_SYSTEM_ERROR, (char*)"ERR_UNKNOWN_SYSTEM_ERROR" },
        { ERR_INVAL_SOCKET, (char*)"ERR_INVAL_SOCKET" },
        { ERR_USER_ID_MISMATCH, (char*)"ERR_USER_ID_MISMATCH" },
        { ERR_INVAL_PUBKEY, (char*)"ERR_INVAL_PUBKEY" },
        { ERR_INVAL_ENTITY_RIGHT, (char*)"ERR_INVAL_ENTITY_RIGHT" },
        { ERR_TRANSACTION_ALIVE, (char*)"ERR_TRANSACTION_ALIVE" },
        { ERR_NOT_USER, (char*)"ERR_NOT_USER" },
        { ERR_NOT_ROLE, (char*)"ERR_NOT_ROLE" },
        { ERR_LIST_DUPLICATE_NOT_ALLOWED, (char*)"ERR_LIST_DUPLICATE_NOT_ALLOWED" },
        { ERR_WF_HOLDER_SELECTION_METHOD_NOT_FOUND, (char*)"ERR_WF_HOLDER_SELECTION_METHOD_NOT_FOUND" },
        { ERR_ABORT_TRANSACTION, (char*)"ERR_ABORT_TRANSACTION" },
        { ERR_COMMIT_TRANSACTION, (char*)"ERR_COMMIT_TRANSACTION" },
        { ERR_TRANSACTION_ABORTED, (char*)"ERR_TRANSACTION_ABORTED" },
        { ERR_TRANSACTION_COMMITED, (char*)"ERR_TRANSACTION_COMMITED" },
        { ERR_READ_ONLY_SLAVE, (char*)"ERR_READ_ONLY_SLAVE" },
        { ERR_DATA_NOT_PRESENT, (char*)"ERR_DATA_NOT_PRESENT" },
        { ERR_OBJECT_NOT_EMBEDDED, (char*)"ERR_OBJECT_NOT_EMBEDDED" },
        { ERR_INTERNAL_PROP_INVALID, (char*)"ERR_INTERNAL_PROP_INVALID" },
        { ERR_INVALID_RUNTIME_ASSIGN, (char*)"ERR_INVALID_RUNTIME_ASSIGN" },
        { ERR_INTERNAL_CLASS_NOTIMPL, (char*)"ERR_INTERNAL_CLASS_NOTIMPL" },
        { ERR_INVALID_COMPONENT, (char*)"ERR_INVALID_COMPONENT" },
        { ERR_RUNTIME_TYPE_MISMATCH, (char*)"ERR_RUNTIME_TYPE_MISMATCH" },
        { ERR_NOT_DEBUGGING, (char*)"ERR_NOT_DEBUGGING" },
        { ERR_SRV_NOT_REGISTERED, (char*)"ERR_SRV_NOT_REGISTERED" },
        { ERR_SERVERTICKET_FORMAT, (char*)"ERR_SERVERTICKET_FORMAT" },
        { ERR_INVAL_CACHE_REGISTER_ID, (char*)"ERR_INVAL_CACHE_REGISTER_ID" },
        { ERR_INVAL_CACHE_ITEM, (char*)"ERR_INVAL_CACHE_ITEM" },
        { ERR_SERVER_NOT_TRUSTED, (char*)"ERR_SERVER_NOT_TRUSTED" },
        { ERR_WSAEINTR_10004, (char*)"ERR_WSAEINTR_10004" },
        { ERR_WSAEBADF_10009, (char*)"ERR_WSAEBADF_10009" },
        { ERR_WSAEACCES_10013, (char*)"ERR_WSAEACCES_10013" },
        { ERR_WSAEFAULT_10014, (char*)"ERR_WSAEFAULT_10014" },
        { ERR_WSAEINVAL_10022, (char*)"ERR_WSAEINVAL_10022" },
        { ERR_WSAEMFILE_10024, (char*)"ERR_WSAEMFILE_10024" },
        { ERR_WSAEWOULDBLOCK_10035, (char*)"ERR_WSAEWOULDBLOCK_10035" },
        { ERR_WSAEINPROGRESS_10036, (char*)"ERR_WSAEINPROGRESS_10036" },
        { ERR_WSAEALREADY_10037, (char*)"ERR_WSAEALREADY_10037" },
        { ERR_WSAENOTSOCK_10038, (char*)"ERR_WSAENOTSOCK_10038" },
        { ERR_WSAEDESTADDRREQ_10039, (char*)"ERR_WSAEDESTADDRREQ_10039" },
        { ERR_WSAEMSGSIZE_10040, (char*)"ERR_WSAEMSGSIZE_10040" },
        { ERR_WSAEPROTOTYPE_10041, (char*)"ERR_WSAEPROTOTYPE_10041" },
        { ERR_WSAENOPROTOOPT_10042, (char*)"ERR_WSAENOPROTOOPT_10042" },
        { ERR_WSAEPROTONOSUPPORT_10043, (char*)"ERR_WSAEPROTONOSUPPORT_10043" },
        { ERR_WSAESOCKTNOSUPPORT_10044, (char*)"ERR_WSAESOCKTNOSUPPORT_10044" },
        { ERR_WSAEOPNOTSUPP_10045, (char*)"ERR_WSAEOPNOTSUPP_10045" },
        { ERR_WSAEPFNOSUPPORT_10046, (char*)"ERR_WSAEPFNOSUPPORT_10046" },
        { ERR_WSAEAFNOSUPPORT_10047, (char*)"ERR_WSAEAFNOSUPPORT_10047" },
        { ERR_WSAEADDRINUSE_10048, (char*)"ERR_WSAEADDRINUSE_10048" },
        { ERR_WSAEADDRNOTAVAIL_10049, (char*)"ERR_WSAEADDRNOTAVAIL_10049" },
        { ERR_WSAENETDOWN_10050, (char*)"ERR_WSAENETDOWN_10050" },
        { ERR_WSAENETUNREACH_10051, (char*)"ERR_WSAENETUNREACH_10051" },
        { ERR_WSAENETRESET_10052, (char*)"ERR_WSAENETRESET_10052" },
        { ERR_WSAECONNABORTED_10053, (char*)"ERR_WSAECONNABORTED_10053" },
        { ERR_WSAECONNRESET_10054, (char*)"ERR_WSAECONNRESET_10054" },
        { ERR_WSAENOBUFS_10055, (char*)"ERR_WSAENOBUFS_10055" },
        { ERR_WSAENOTCONN_10057, (char*)"ERR_WSAENOTCONN_10057" },
        { ERR_WSAESHUTDOWN_10058, (char*)"ERR_WSAESHUTDOWN_10058" },
        { ERR_WSAETOOMANYREFS_10059, (char*)"ERR_WSAETOOMANYREFS_10059" },
        { ERR_WSAELOOP_10062, (char*)"ERR_WSAELOOP_10062" },
        { ERR_WSAENAMETOOLONG_10063, (char*)"ERR_WSAENAMETOOLONG_10063" },
        { ERR_WSAEHOSTDOWN_10064, (char*)"ERR_WSAEHOSTDOWN_10064" },
        { ERR_WSAEHOSTUNREACH_10065, (char*)"ERR_WSAEHOSTUNREACH_10065" },
        { ERR_WSAENOTEMPTY_10066, (char*)"ERR_WSAENOTEMPTY_10066" },
        { ERR_WSAEPROCLIM_10067, (char*)"ERR_WSAEPROCLIM_10067" },
        { ERR_WSAEUSERS_10068, (char*)"ERR_WSAEUSERS_10068" },
        { ERR_WSAEDQUOT_10069, (char*)"ERR_WSAEDQUOT_10069" },
        { ERR_WSAESTALE_10070, (char*)"ERR_WSAESTALE_10070" },
        { ERR_WSAEREMOTE_10071, (char*)"ERR_WSAEREMOTE_10071" },
        { ERR_WSASYSNOTREADY_10091, (char*)"ERR_WSASYSNOTREADY_10091" },
        { ERR_WSAVERNOTSUPPORTED_10092, (char*)"ERR_WSAVERNOTSUPPORTED_10092" },
        { ERR_WSANOTINITIALISED_10093, (char*)"ERR_WSANOTINITIALISED_10093" },
        { ERR_WSAEISCONN, (char*)"ERR_WSAEISCONN" },
        { ERR_WSACONNREFUSED, (char*)"ERR_WSACONNREFUSED" },
        { ERR_WSAETIMEDOUT_10060, (char*)"ERR_WSAETIMEDOUT_10060" },
        { ERR_THREAD_RUNNING, (char*)"ERR_THREAD_RUNNING" },
        { ERR_THREAD_NOT_FOUND, (char*)"ERR_THREAD_NOT_FOUND" },
        { ERR_FOREIGN_OBJECT, (char*)"ERR_FOREIGN_OBJECT" },
        { ERR_RULE_INVALID_SPACE, (char*)"ERR_RULE_INVALID_SPACE" },
        { ERR_RULE_NO_MATCH_CONTENT, (char*)"ERR_RULE_NO_MATCH_CONTENT" },
        { ERR_RULE_NO_MATCH_FOLDER, (char*)"ERR_RULE_NO_MATCH_FOLDER" },
        { ERR_UPDATES_NON_AVAIL, (char*)"ERR_UPDATES_NON_AVAIL" },
        { ERR_UPDATES_CREATE_FAIL, (char*)"ERR_UPDATES_CREATE_FAIL" },
        { ERR_UPDATES_INVAL_OPSYS, (char*)"ERR_UPDATES_INVAL_OPSYS" },
        { ERR_ALREADY_ROLE_MEMBER, (char*)"ERR_ALREADY_ROLE_MEMBER" },
        { ERR_SSL_ERROR_ZERO_RETURN, (char*)"ERR_SSL_ERROR_ZERO_RETURN" },
        { ERR_SSL_ERROR_WANT_READ, (char*)"ERR_SSL_ERROR_WANT_READ" },
        { ERR_SSL_ERROR_WANT_WRITE, (char*)"ERR_SSL_ERROR_WANT_WRITE" },
        { ERR_SSL_ERROR_WANT_CONNECT, (char*)"ERR_SSL_ERROR_WANT_CONNECT" },
        { ERR_SSL_ERROR_WANT_ACCEPT, (char*)"ERR_SSL_ERROR_WANT_ACCEPT" },
        { ERR_SSL_ERROR_WANT_X509_LOOKUP, (char*)"ERR_SSL_ERROR_WANT_X509_LOOKUP" },
        { ERR_SSL_ERROR_SYSCALL, (char*)"ERR_SSL_ERROR_SYSCALL" },
        { ERR_COULD_NOT_READ_ACL, (char*)"ERR_COULD_NOT_READ_ACL" },
        { ERR_AUTH_MECH_NOT_ALLOWED, (char*)"ERR_AUTH_MECH_NOT_ALLOWED" },
        { ERR_FRAMESTACK_LEVEL_EXCEEDED, (char*)"ERR_FRAMESTACK_LEVEL_EXCEEDED" },
        { ERR_SOFTRULES_DENIED_PLACEMENT, (char*)"ERR_SOFTRULES_DENIED_PLACEMENT" },
        { ERR_REGEX_FAILURE, (char*)"ERR_REGEX_FAILURE" },
        { ERR_SERVER_PURGING, (char*)"ERR_SERVER_PURGING" },
        { ERR_SERVER_PURGED, (char*)"ERR_SERVER_PURGED" },
        { ERR_SERVER_MUST_PURGE, (char*)"ERR_SERVER_MUST_PURGE" },
        { ERR_INVALID_IMAGE, (char*)"ERR_INVALID_IMAGE" },
        { ERR_INVALID_FILE, (char*)"ERR_INVALID_FILE" },
        { ERR_NEW_SPACE_OFFLINE, (char*)"ERR_NEW_SPACE_OFFLINE" },
        { ERR_SERVER_NOT_AVAILABLE, (char*)"ERR_SERVER_NOT_AVAILABLE" },
        { ERR_PARSER_ERROR, (char*)"ERR_PARSER_ERROR" },
        { ERR_NOT_SERVICE, (char*)"ERR_NOT_SERVICE" },
        { ERR_SERVICE_NOT_ACTIVE_1062, (char*)"ERR_SERVICE_NOT_ACTIVE_1062" },
        { ERR_FAILED_SERVICE_CONTROLLER_CONNECT_1063, (char*)"ERR_FAILED_SERVICE_CONTROLLER_CONNECT_1063" },
        { ERR_NO_OF_ENVIRON, (char*)"ERR_NO_OF_ENVIRON" },
        { ERR_DELETE_IN_DESTRUCTOR, (char*)"ERR_DELETE_IN_DESTRUCTOR" },
        { ERR_INVAL_CODE, (char*)"ERR_INVAL_CODE" },
        { ERR_INVAL_RESPONSE, (char*)"ERR_INVAL_RESPONSE" },
        { ERR_INVAL_TYPE, (char*)"ERR_INVAL_TYPE" },
        { ERR_PRINTS_ARG_COUNT, (char*)"ERR_PRINTS_ARG_COUNT" },
        { ERR_SPACERULE_NOT_FOUND, (char*)"ERR_SPACERULE_NOT_FOUND" },
        { ERR_SERVER_TERMINATING, (char*)"ERR_SERVER_TERMINATING" },
        { ERR_CLASS_IDNAME_MISMATCH, (char*)"ERR_CLASS_IDNAME_MISMATCH" },
        { ERR_SYSCLM_CLASS_MISMATCH, (char*)"ERR_SYSCLM_CLASS_MISMATCH" },
        { ERR_SERVER_NAMEID_MISMATCH, (char*)"ERR_SERVER_NAMEID_MISMATCH" },
        { ERR_INVALID_ADMIN_FUNC, (char*)"ERR_INVALID_ADMIN_FUNC" },
        { ERR_DEMOUSER_EXPIRED, (char*)"ERR_DEMOUSER_EXPIRED" },
        { ERR_BUILDING, (char*)"ERR_BUILDING" },
        { ERR_NO_CURRENT_USER, (char*)"ERR_NO_CURRENT_USER" },
        { ERR_INCOMPAT_SERVER, (char*)"ERR_INCOMPAT_SERVER" },
        { ERR_NEED_LOCK, (char*)"ERR_NEED_LOCK" },
        { ERR_LOCK_HELD, (char*)"ERR_LOCK_HELD" },
        { ERR_LOCK_YOURS, (char*)"ERR_LOCK_YOURS" },
        { ERR_XML_PARSE_XPATH, (char*)"ERR_XML_PARSE_XPATH" },
        { ERR_WSDL_CANNOT_FIND_WSDLPPITEM, (char*)"ERR_WSDL_CANNOT_FIND_WSDLPPITEM" },
        { ERR_WSDL_CANNOT_FIND_TARGET_NAMESPACE, (char*)"ERR_WSDL_CANNOT_FIND_TARGET_NAMESPACE" },
        { ERR_BUFFER_TOO_SMALL, (char*)"ERR_BUFFER_TOO_SMALL" },
        { ERR_NONCE_EXPIRED, (char*)"ERR_NONCE_EXPIRED" },
        { ERR_NOT_DICTIONARY_SERVER, (char*)"ERR_NOT_DICTIONARY_SERVER" },
        { ERR_HOME_DICTIONARY_MISMATCH, (char*)"ERR_HOME_DICTIONARY_MISMATCH" },
        { ERR_INVAL_ACCESS_FUNCTION, (char*)"ERR_INVAL_ACCESS_FUNCTION" },
        { ERR_HOMESERVER_NOTAVAIL, (char*)"ERR_HOMESERVER_NOTAVAIL" },
        { ERR_OBJECT_NAME_EMPTY, (char*)"ERR_OBJECT_NAME_EMPTY" },
        { ERR_INVAL_ATTACHMENT, (char*)"ERR_INVAL_ATTACHMENT" },
        { ERR_SSL_DECRYPT, (char*)"ERR_SSL_DECRYPT" },
        { ERR_TOO_MANY_SITES, (char*)"ERR_TOO_MANY_SITES" },
        { ERR_SSO_FAILED, (char*)"ERR_SSO_FAILED" },
        { -1, (char*)"END" }
    };
    const char *val = 0;
    for ( ofuint32 x = 0; !val && names[x].index != -1; x++ )
        if ( names[x].index == (ofint32)enumValue )
        {
            val = names[x].name;;
        }
    return val;
}

/* B */
const char *
translate_OPSYS2( ofuint32 enumValue )
{
    struct NAMEPAIR { ofint32 index; char *name; };
    NAMEPAIR names[] = {
        { OS_LINUX, (char*)"OS_LINUX" },
        { OS_WIN9X, (char*)"OS_WIN9X" },
        { OS_WINME, (char*)"OS_WINME" },
        { OS_WINNT, (char*)"OS_WINNT" },
        { OS_WIN2K, (char*)"OS_WIN2K" },
        { OS_WINXP, (char*)"OS_WINXP" },
        { OS_MACOS, (char*)"OS_MACOS" },
        { OS_MACOSX, (char*)"OS_MACOSX" },
        { OS_SOL8, (char*)"OS_SOL8" },
        { OS_SOL9, (char*)"OS_SOL9" },
        { OS_FREEBSD, (char*)"OS_FREEBSD" },
        { OS_DARWIN, (char*)"OS_DARWIN" },
        { OS_SOLARIS, (char*)"OS_SOLARIS" },
        { -1, (char*)"END" }
    };
    const char *val = 0;
    for ( ofuint32 x = 0; !val && names[x].index != -1; x++ )
        if ( names[x].index == (ofint32)enumValue )
        {
            val = names[x].name;;
        }
    return val;
}


/* D */
ofuint32
translate_OFVALUE_TYPES_rev( const char *enumName )
{
    struct NAMEPAIR { ofint32 index; char *name; };
    NAMEPAIR names[] = {
        { typeInteger, (char*)"typeInteger" },
        { typeBoolean, (char*)"typeBoolean" },
        { typeString, (char*)"typeString" },
        { typeFloat, (char*)"typeFloat" },
        { typeOFDateTime, (char*)"typeOFDateTime" },
        { typeIdentity, (char*)"typeIdentity" },
        { typeBinary, (char*)"typeBinary" },
        { -1, (char*)"END" }
    };
    ofuint32 index = 0;
    for ( ofuint32 x = 0; !index && names[x].index != -1; x++ )
        if ( !OFOS::stricmp( names[x].name, enumName) )
        {
            index = names[x].index;
        }
    return index;
}


/* E */
ofuint32
translate_OFVALUE_TYPES_rev_desc( const char *enumName )
{
    struct NAMEPAIR { ofint32 index; char *name; };
    NAMEPAIR names[] = {
        { typeInteger, (char*)"integer" },
        { typeBoolean, (char*)"boolean" },
        { typeString, (char*)"string" },
        { typeFloat, (char*)"float" },
        { typeOFDateTime, (char*)"datetime" },
        { typeIdentity, (char*)"identity" },
        { typeBinary, (char*)"binary" },
        { -1, (char*)"END" }
    };
    ofuint32 index = 0;
    for ( ofuint32 x = 0; !index && names[x].index != -1; x++ )
        if ( !OFOS::stricmp( names[x].name, enumName) )
        {
            index = names[x].index;
        }
    return index;
}




